### ISSUE TITLE
Support running `tsc --noEmit` before transpiling

### ISSUE THREAD

**Issue by aminya** [esbuild-kit/tsx#121]
### Feature request

It would be nice to add an option so that tsx runs `tsc --noEmit` before transpiling

### Why?

Type-checking is important, and only relying on the IDE checker is not enough. The dependencies of a project change, and those can introduce new type errors. But because I haven't opened that file, the IDE doesn't check it.

### Alternatives

Wrapping `tsx` so that it calls `tsc --noEmit file` before tsx

**Comment by privatenumber** [comment]
Blocking execution with type-checking kind of defeats the point of tsx. If you want to do that, why not just run tsc and use Node to run the compiled file?

Also, you can run this yourself:

```sh
tsc --noEmit ./file.ts && tsx ./file.ts
```

Or wrap it in a `package.json` script.
