### ISSUE TITLE
Ability to avoid sending `dependency` messages

### ISSUE THREAD

**Issue by JoostK** [esbuild-kit/tsx#131]
### Feature request

Firstly, thanks for this excellent project!

I am using `tsx` in a setup where there's other worker communication happening, and the `{type: 'dependency'}` message that is sent by the ESM and CJS loaders is causing failures because of an unknown message. Although this could be considered a bug with those tools, I am opening an issue here to request a mode where the loaders do not send messages. 

The code has a comment saying these messages are for watch-mode, perhaps those messages can only be sent if watch mode is known to be active? Alternatively an environment variable could work.

### Why?

I am experimenting with using `tsx` and its CJS and ESM loaders together with `jest-light-runner` to achieve a Jest setup without any Jest transforms, which results in an incredible performance improvement over using stock Jest and its isolated module system. Using Jest workers however results in failures because of the unknown message from `tsx`'s loaders.

### Alternatives

The issue is avoided if you first run Jest using `--runInBand` because this populates all caches after which multiple workers do work, because the `{type: 'dependency'}` message would no longer be sent.

### Additional context

https://github.com/esbuild-kit/esm-loader/blob/d50ddacab0c0df8ee3ccafc75272d28889fb90fd/src/loaders.ts#L212-L217

https://github.com/esbuild-kit/cjs-loader/blob/e7ba7caf42cb1bdceacb0bcafd2db3fd747931c0/src/index.ts#L54-L59

I am willing to work on this myself, but would like to discuss the possibilities here before spending any time on it.

**Comment by privatenumber** [comment]
You should file a bug with the tool that's throwing the error.

Especially if it's a tool that's designed to run user-code, it should create it's own IPC namespace instead of expecting to be the only one on it.

**Comment by privatenumber** [comment]
Closing as the error is thrown by another tool, and there's no further discussion.
