### ISSUE TITLE
bug: all dependencies getting compiled in strict mode

### ISSUE THREAD

**Issue by dylang** [esbuild-kit/tsx#132]
### Bug description

> [Fixed in esbuild v0.15.8](https://hyrious.me/esbuild-repl/?version=0.15.8&mode=transform&options=--loader%3Dts+--format%3Dcjs+--tsconfig-raw%3D%27%7B+%22compilerOptions%22%3A+%7B%22alwaysStrict%22%3A+true%7D+%7D%27)
> 
> However, this leads to a bug in tsx where all dependencies getting compiled in strict mode. Will fix.

Hi - this adding unexpected issues to our code.

### Reproduction

0.  `esbuild` newer than `0.15.7` (it's not broken in 0.15.7).
1.  Add an old module that doesn't use strict mode: `yarn add node-excel-export`
2.  Run tsx: `yarn tsx`
3.  Require it in the REPL: `require('node-excel-export')`

Result:

```
Welcome to Node.js v16.15.0.
Type ".help" for more information.
> require('node-excel-export')
Uncaught ReferenceError: cptable is not defined
    at make_xlsx (/Users/dgreene/medallia/reporting-prs/node_modules/xlsx-style/xlsx.js:2:339)
    at /Users/dgreene/medallia/reporting-prs/node_modules/xlsx-style/xlsx.js:2:328391
    at Object.<anonymous> (/Users/dgreene/medallia/reporting-prs/node_modules/xlsx-style/xlsx.js:3:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.v (/Users/dgreene/medallia/reporting-prs/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:901)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

### Environment

```shell
System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 130.82 MB / 32.00 GB
    Shell: 3.5.0 - /usr/local/bin/fish
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
```

```
yarn why esbuild
=> Found "esbuild@0.15.12"
```
```


### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by dylang** [comment]
Hi @privatenumber - 

I decided that our goals aren't the same and it would be best to build our own ESM loader using babel-core so you don't need to make changes you don't want and we're not blocked by bugs introduced by nuances in ESBuild.

I truly appreciate your hard work on this project. You helped us finally be able to use third-party ESM modules. I hope we can use your work again in the future.

**Comment by privatenumber** [comment]
It's still a bug.

**Comment by GauBen** [comment]
Hey there!

Here's a workaround: run `tsx --tsconfig tsconfig.runtime.json file.ts` with 

```jsonc
// tsconfig.runtime.json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "strict": false
  }
}
```
