### ISSUE TITLE
Don't remove whitespace when debugging file

### ISSUE THREAD

**Issue by hansottowirtz** [esbuild-kit/tsx#143]
### Feature request

When using `tsx --inspect` or `tsx --inspect-brk` and `debugger`, all Typescript code is put on one line, making it very hard to debug using DevTools.

### Why?

The lack of newlines makes navigating the executing script very hard. This is the only reason we're sometimes falling back to `ts-node`.

### Alternatives

You can press the format button (`{}`) inside DevTools which will format the file, but you have to do it for every individual file and it's very tedious.

I've also disabled sourcemaps in DevTools because it makes it harder to debug some of my projects. Enabling it would solve the issue for most files, but I'd really like to be able to use it without sourcemaps enabled as well.

### Additional context

Example:

`test.ts`
```ts
import { jsonSha256 } from "../../src/util/json-sha256"
import * as util from "../../src/util/util"
import { init } from "../script-init";

console.log(util, init, jsonSha256);

debugger;
```

running `tsx --inspect-brk test.ts`

turns into:

<img width="1400" alt="Screenshot 2022-11-12 at 16 52 49" src="https://user-images.githubusercontent.com/5406212/201482550-93bdb7bf-e09d-40a7-8e1f-cdf551122441.png">

**Comment by privatenumber** [comment]
Can you provide a screenshot of your Devtools settings to check if you have Source maps enabled?

**Comment by hansottowirtz** [comment]
I had this setting disabled on purpose, but I cannot remember why exactly I disabled them. I assume it was because of an Angular project, because I wanted to see the compiled output instead of the source, as there are a lot of transformations going on.

If I understand correctly, when using tsx you should never want to see the compiled output?

In that case, I'll open a PR to document `--inspect` and `--inspect-brk` and the need to enable the "Enable Javascript source maps" setting.

If there are some cases where someone would like to see the compiled output, it would still be helpful to turn off the minification in esbuild.

**Comment by privatenumber** [comment]
Thanks but I would like to keep tsx documentation specific to usage, and enabling source maps is standard practice in JavaScript debugging so I don't think it's necessary.

The compiled code is minified for smaller cache size and (marginally) faster transformation. But it's only removing white space so clicking on `{}` should sufficiently prettify it to show the compiled output for those that are interested.
