### ISSUE TITLE
Environment variables not loading correctly using dotenv 

### ISSUE THREAD

**Issue by MoSheikh** [esbuild-kit/tsx#146]
### Bug description

When watching a project from a specified root, any `dotenv` configs that should be loaded from that root are ignored. Thus environement variables are not available to be used in the application. In other solutions similar to `tsx`, such as `ts-node-dev`, the environment variables are loaded correctly. 

### Reproduction

[Reproduced bug](https://github.com/MoSheikh/tsx-bug)

### Environment

```shell
System:
  OS: macOS 12.6.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 94.16 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.13.0 - /usr/local/bin/node
  npm: 8.1.0 - /usr/local/bin/npm
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
This is expected behavior as per ESM spec and is reproducible in Node.js as well in ESM mode.

In ESM, all imports in a file resolved and executed before the code in the file, even if the `import` happens at the end of the file.

In this [demo](https://stackblitz.com/edit/node-wn7dxg?file=index.js), notice how `2` is logged before `1`, despite `console.log(1)` being before the import.

So your file `main.ts`:

```js
import * as dotenv from "dotenv";

dotenv.config({ path: "./.env" });

import { EXTERNAL_IMPORT } from "./external";

console.log(`EXTERNAL_IMPORT: ${EXTERNAL_IMPORT}`);
```

Is getting executed as:

```js
import * as dotenv from "dotenv";
import { EXTERNAL_IMPORT } from "./external";

dotenv.config({ path: "./.env" });

console.log(`EXTERNAL_IMPORT: ${EXTERNAL_IMPORT}`);
```

That said, dotenv is not loading the `.env` dotenv file until after `./external` is loaded.

**Comment by MoSheikh** [comment]
Thanks for the explanation @privatenumber, I've worked around this by adding the `dotenv` import and initialization to a separate module `env.ts`, which I import first from `main.ts`. This leads to correct behaviour since the imported module is executed first. Appreciate the help!

`main.ts:`
```ts
import "./env";
import { EXTERNAL_IMPORT } from "./external";

console.log(`EXTERNAL_IMPORT: ${EXTERNAL_IMPORT}`);
```

`env.ts:`
```ts
import * as dotenv from "dotenv";

dotenv.config({ path: "./.env" });
```


`external.ts:`
```ts
export const EXTERNAL_IMPORT = 1;

console.log(`process.env.TSX_TEST: ${process.env.TSX_TEST}`);
```

**Comment by privatenumber** [comment]
If your dotenv file is actually called `.env`, you should be able to replace `import ".env"` with `import 'dotenv/config'` so you can remove `env.ts`.

**Comment by MoSheikh** [comment]
Thank you! In another monorepo project I'm using an additional `.env` from an ancestor directory so the default import isn't sufficient but in this case that's perfect.
