### ISSUE TITLE
Add `--watch` option

### ISSUE THREAD

**Issue by takegine** [esbuild-kit/tsx#148]
### Feature request

Add `--watch` option

### Why?

When I am coding a `ts` file, I want to listen for file changes. I used to use `nodemon`, but it uses `ts-node`. I hope it can use `tsx` or support this function directly without run a `nodemon`

### Additional context

```json
{
    "scripts":{
        "launch": "tsx src",
        "dev": "tsx src --watch"
        // "dev": "nodemon src/index.ts"
    }
}
```

**Comment by privatenumber** [comment]
Please read the README:
https://github.com/esbuild-kit/tsx#watch-mode

**Comment by takegine** [comment]
If it is `tsx --watch`, I can use it in the `package.json`, but the `tsx watch `.
```json
  "scripts": {
    "build": "run-p build:*",
    "build:server": "tsx main",
    "dev": "npm run build -- --watch",
}

```
