### ISSUE TITLE
tsconfig path

### ISSUE THREAD

**Issue by rmcarias** [esbuild-kit/tsx#15]
I am trying to send an explicit tsconfig path
```
esno --tsconfig=tsconfig.server.json ./server/**/*.ts 
```
and it doesn't seem to allow any other args (at least those supported by esbuild)
```v16.0.0/bin/node: bad option: --tsconfig=tsconfig.server.json```
How do I work around this?

**Comment by amitdahan** [comment]
Hey! I'd love to contribute this. 

Would you accept a PR adding `tsx --tsconfig tsconfig.custom.json` that'll somehow propagate the `configName` arg to `get-tsconfig`?

**Comment by privatenumber** [comment]
Sure. I'm still haven't thought of the best way to communicate that down to the loaders but I'm open to ideas.

**Comment by amitdahan** [comment]
I thought about either:


### Env var
We could use a new `ESBK_TSCONFIG_PATH` env var.
This would be exactly the same as already done with `ESBK_DISABLE_CACHE` if I'm not mistaken.

### ESM query
We could technically resolve `tsx`'s `src/loader.ts` with a `src/index.ts?tsconfig=...` query.

Then, for CJS we could pretty easily just pass the path down via:

```diff ts
```

And then we could forward this from our ESM `loader.ts` entry into `cjs-loader` via a `register()` function that could accept it.

For ESM we could just keep forwarding the query:

```diff
-export * from '@esbuild-kit/esm-loader';
+export * from '@esbuild-kit/esm-loader';
```

**Comment by privatenumber** [comment]
I agree the env var solution works best, also because we need to provide an API for the loaders to be used standalone.
