### ISSUE TITLE
Support for `satisfies`

### ISSUE THREAD

**Issue by baptisteArno** [esbuild-kit/tsx#153]
### Bug description

Currently, tsx doesn't recognize the `satisfies` typescript keyword.

### Reproduction

Try to compile:

```ts
const test = {name: 'John'} satisfies {name: string}
```

### Environment

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 96.28 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    npm: 8.19.2 - /opt/homebrew/bin/npm
  npmPackages:
    tsx: 3.12.1 => 3.12.1
```

### Can you contribute a fix?

- [X] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Works fine for me. You probably just need to update esbuild (`npm update` or re-install `tsx`).

Please provide a link to reproduction if it still doesn't work.

**Comment by baptisteArno** [comment]
Adding this to my `package.json`: `"esbuild": "0.15.16"` fixes the issue. But I'd rather not do that 🤔

Any idea why `tsx` resolves to `node_modules/.pnpm/esbuild@x` ?

**Comment by baptisteArno** [comment]
Another package in my monorepo is using `tsup@6.5.0`, that's probably linked as they use `esbuild@^0.15.1`

**Comment by baptisteArno** [comment]
I guess it has nothing to do with `tsx` then 😁

Thank you for your help!

**Comment by privatenumber** [comment]
To prevent pnpm from optimizing the shared dependencies, I think you can just install tsx to the specific project instead of the root.

Also, checkout [pkgroll](https://github.com/privatenumber/pkgroll) for a no-config alternative to tsup!
