### ISSUE TITLE
using tsx instead of ts-node messes up code coverage calculations

### ISSUE THREAD

**Issue by electrovir** [esbuild-kit/tsx#155]
### Bug description

I use [nyc](https://www.npmjs.com/package/nyc) to calculate code coverage in tests.

When using `tsx` for `require` in a mocha config to run typescript test files, code coverage always reports that line `1` in test files is missing branch coverage. This does not happen if `ts-node` is used for mocha's `require` config.

I am interested in helping out with a fix but I don't know where I would start 😕. I'm guessing this is related to source maps.

### Reproduction

https://github.com/electrovir/tsx-code-coverage-bug

run `npm start` within that repo

### Environment

```shell
System:
  OS: macOS 13.0.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 308.66 MB / 32.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
  npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
npmPackages:
  tsx: ^3.12.1 => 3.12.1
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
I'm not fully convinced there's a bug in `tsx`.

Your reproduction isn't minimal which makes it hard to debug. There are too many variables at play that can be a point of failure: it's possible your `nyc`/`mocha` configuration is incorrect, and it's also possible `ts-node` has custom support for `nyc`.

Try reducing your reproduction even further:
- TypeScript: Do you _need_ it to reproduce the bug? Try reproducing it with plain JS
- Mocha: Do you need this to reproduce the coverage bug? Try removing it and use plain Node.js
- `@istanbuljs/nyc-config-typescript`: Remove and inline contents. Remove what you don't need
- `tsx`: You're only using CommonJS transformation. Remove and replace with `@esbuild-kit/cjs-loader`. 
- Remove *everything* that doesn't contribute to the reproduction: unused files, dependencies, redundant scripts, meta data

I also encourage you to open an issue with nyc to figure out what just-in-time compilers need to add support. I've never used `nyc` before so you won't have any luck here.

**Comment by electrovir** [comment]
Thanks for the tips! I will continue to investigate and report back here.
