### ISSUE TITLE
tsx does not pass experimental flags down to node

### ISSUE THREAD

**Issue by sidwebworks** [esbuild-kit/tsx#156]
### Bug description

I tested my server by manually compiling it using `tsc` and running `node  --experimental-wasm-threads ./server.js` which solved my issue, but I don't know if it's a bug in `tsx` or is there something I am missing. 

### Reproduction

```
tsx watch --experimental-wasm-threads ./src/server.ts
```

### Environment

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 61.97 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  npmPackages:
    tsx: ^3.12.1 => 3.12.1
```

### Can you contribute a fix?

- [X] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Please provide a reproduction
