### ISSUE TITLE
watch ignore is broken

### ISSUE THREAD

**Issue by amirrezamahyari** [esbuild-kit/tsx#169]
### Bug description

after upgrading to version [3.12.1](https://github.com/esbuild-kit/tsx/releases/tag/v3.12.1) ignore is broken

seems this PR caused of that [cb89f95](https://github.com/esbuild-kit/tsx/commit/cb89f95ba5274833fcea033c8c818c829c5e02be)

raw args is :
![Screenshot 2022-12-31 at 4 16 41 PM](https://user-images.githubusercontent.com/20089037/210137305-5ba42df3-d995-4274-a234-6c4695836f22.jpg)

but argv returns : 

![Screenshot 2022-12-31 at 4 16 49 PM](https://user-images.githubusercontent.com/20089037/210137338-b321f1ac-11e3-4667-ad24-76a41c056884.jpg)

### Reproduction

`tsx watch ./src/index.ts --clear-screen=false --ignore ../../../packages/shared/src/schema/**/*`

### Environment

```shell

  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 546.59 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  npmPackages:
    tsx: 3.12.0 => 3.12.0
```

**Comment by privatenumber** [comment]
The previous behavior was a bug. This behavior is correct and mirrors Node.js.

To pass flags into watch, place them right after `watch` and before the file path:

```
tsx watch --clear-screen=false --ignore ../../../packages/shared/src/schema/**/* ./src/index.ts
```

All argvs after the file path are passed into the file for the file to handle via `process.argv`.

This behavior allows users to control what flags go to tsx, and what goes to the file being executed.
