### ISSUE TITLE
Bump esbuild

### ISSUE THREAD

**Issue by stephenh** [esbuild-kit/tsx#171]
### Bug description

Writing TypeScript code that uses the new TS 4.9 `satisifies` operator does not work in esbuild 0.15.x.

I can `yarn add --dev esbuild` to get esbuild 0.16.x, but b/c minor versions are considered semver incompitable, tsx / `@esbuild-kit/core-utils` keeps a shadowed version of esbuild 0.15.x, which I can also fix by adding a `resolutions` for 0.16.x.

But would be great to just bump tsx to the latest and get the latest esbuild (understood you don't want to do that for _every_ single esbuild release, but it's been awhile / there is a new 'major' minor version, so seems worth it)

Thanks!

### Reproduction

Write TS code with `satisifies`, like trivial example:

```
const a = 1 satisfies number;
```

### Environment

```shell
n/a
```

### Can you work on a fix?

- [X] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment]
PR welcome!

**Comment by privatenumber** [comment]
Actually, I'm going to close this out because you're reporting that `satisfies` doesn't work, but it should.

Previously reported in:
https://github.com/esbuild-kit/tsx/issues/153

`satisfies` was added in v0.15, not. v0.16:
https://github.com/evanw/esbuild/releases/tag/v0.15.13

Regardless, if you can articulate a concrete motivation to bump esbuild other than "house keeping", I'm happy to accept a PR.

**Comment by stephenh** [comment]
Ah gotcha; I had bumped to the latest tsx, 3.12.1, and that only got me to esbuild 0.15.11:

```
$ yarn why esbuild
└─ @esbuild-kit/core-utils@npm:3.0.0
   └─ esbuild@npm:0.15.11 (via npm:~0.15.10)
```

And my initial "just add an explicit esbuild 0.16.x to package.json" fix did not work (because tsx kept using the shadowed 0.15.11), so once I `resolution`-d `0.16.x` and "hey it worked!", I jumped to the conclusion that it was `0.16.x` release that added the `satisifies` support.

But, gotcha, you're right, the real issue was that (sans a `resolutions` entry), I should have added `esbuild 0.15.13` (or whatever latest `0.15.x` release) to my package.json.

So, dunno, despite my incorrect assumption about which esbuild version introduced `satisifies` support, it still seems worth bumping the current `core-utils` dep on esbuild `~0.15.10` to at least `0.15.13` and maybe just going to the latest `0.16.x` while at it?

Thanks!

**Comment by privatenumber** [comment]
You don't need to use `resolution`. As said in https://github.com/esbuild-kit/tsx/issues/153, you can just run `npm update` (or [`yarn upgrade`](https://shift.infinite.red/npm-vs-yarn-cheat-sheet-8755b092e5cc#:~:text=add%20taco%20%2D%2Ddev-,npm%20update%20%2D%2Dsave,-%3D%3D%3D%20yarn%20upgrade)?) and it will update your nested dependencies.

> So, dunno, despite my incorrect assumption about which esbuild version introduced `satisifies` support, it still seems worth bumping the current `core-utils` dep on esbuild `~0.15.10` to at least `0.15.13` and maybe just going to the latest `0.16.x` while at it?

As I said earlier, if you can **articulate a concrete motivation** to bump esbuild other than "house keeping", I'm happy to accept a PR.

**Comment by stephenh** [comment]
Huh.

Frankly I thought my use case of "I manually edited `package.json` to the latest and expected things to work" was a good enough rationale (that's why I filed the issue in the first place), because even if `yarn up --recursive esbuild` does pedantically work, I anticipate a lot of other users like myself expect the "just edit package.json" to generally work.

Or, if not manually editing package.json, I would have expected running `yarn up tsx` to fix it, but that doesn't upgrade esbuild b/c tsx's latest `package.json` asserts that my local `0.15.10` is "still good!". But it's not.

I have to dig in and realize "oh right, tsx uses esbuild, and I need a newer esbuild ... and thankfully only the latest 0.15.x build, so yep I can `yarn up --recursive` instead of using `resolutions`".

So, yeah, you are technically/pedantically right, but:

a) this still seems like a foot gun for existing users (they must know to use `yarn up --recursive esbuild`), and

b) it's only correct because the bug that matters to me _happens_ to have been fixed in a `0.15.x` release, which afaiu is finished/not getting backports; once any tsx users wants a feature + bug fix + improvement from the `0.16.x` series of esbuild, they're going to need to use `resolutions`.

I get you don't want to release a new tsx for every single little patch version of esbuild, b/c there are a lot of them, but :shrug: both:

1) a non-working TS keyword for existing tsx users that don't know/perform exactly the right upgrade strategy, and:

2) getting onto the latest major semver version of esbuild

Both seem like "more than housekeeping" rationale for bumping esbuild imo.

But, we can stop arguing about it; my project is working, and was already working before I filed the bug, I was just trying to help other users, so I'm good.

**Comment by privatenumber** [comment]
I agree it's not the best workflow. But as you've mentioned, releasing an update for each esbuild version creates a lot of unnecessary work and isn't sustainable.

I prefer users learn how to update nested dependencies through package managers instead—the skill will be beneficial in general Node.js development.

Thanks for your consideration, nonetheless.

**Comment by stephenh** [comment]
TypeScript 5.x has a new `const` syntax that will require an esbuild 0.17.x release:

https://github.com/evanw/esbuild/releases/tag/v0.17.5

Granted, it is worth waiting until TS 5.0 final is out before bumping, but just putting on your radar that this is a not-fixed-in-0.15.x issue that I think tsx users would enjoy having just work out of the box + not having to use `resolutions`.

`:ducks:` :-)

**Comment by privatenumber** [comment]
You're welcome to open a PR

**Comment by stephenh** [comment]
@privatenumber awesome! Thanks! :-)

I'll probably wait until TS 5.x final comes out, unless someone beats me to it.
