### ISSUE TITLE
Allow scripts to be run without a file extension

### ISSUE THREAD

**Issue by engina** [esbuild-kit/tsx#175]
### Feature request

A command line parameter to tsx to force extension.

### Why?

It's slower to type the script name with the extension, especially because `.` character is in an inconvenient place.
```
./script.mts
```
Or if it's in your path
```
script.mts
```

### Alternatives

Enfore extension in the shebang

```
#!/usr/bin/env -S tsx --type=mts
```

### Additional context

And when you add the script to the PATH it will be just another tool in your work environment.

**Comment by privatenumber** [comment]
Sorry I don't understand the request.

Can you elaborate on your use-case?

**Comment by engina** [comment]
What I meant was:

```bash
> cat test.mts 
#!/usr/bin/env tsx
console.log('hello');
> ./test.mts
hello
> cp test.mts test
> chmod u+x test
> ./test
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /Users/engin/code/cliui/test
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:87:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:102:38)
    at defaultLoad (node:internal/modules/esm/load:21:14)
    at x (file:///Users/engin/.local/share/nvm/v16.14.0/lib/node_modules/tsx/node_modules/@esbuild-kit/esm-loader/dist/index.js:1:2902)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

**Comment by privatenumber** [comment]
Sorry, I'm not interested in this enhancement.

Explicit extensions are enforced by Node.js as a part of ESM.

You can file the request with Node.js or add your own custom Node.js loader though.

**Comment by tonyxiao** [comment]
> ```
> #!/usr/bin/env -S tsx --type=mts
> ```

@engina is this actually working? Or is it your proposed solution? I'm getting an error `bin/node: bad option: --type=mts` when I add it.

**Comment by engina** [comment]
> > ```
> > #!/usr/bin/env -S tsx --type=mts
> > ```
> 
> @engina is this actually working? Or is it your proposed solution? I'm getting an error `bin/node: bad option: --type=mts` when I add it.

It was my proposed solution. It won't work for you.

I ended up doing a Makefile and a shell alias.

```Makefile
# Makefile
dist/ecm.js: $(shell find apps/ecm/src/ -type f)
	esbuild apps/ecm/src/main.ts --platform=node --bundle --minify --outfile=dist/ecm.js
```

```bash
alias ecm='make -s dist/ecm.js; node dist/ecm.js
```

This compiles the ts command line utulity if source codes are changed. If not , just runs it the already compiled version.

Even in the "cold boot" where it compiles and runs the tool, it does it faster than tsx.

`tsx apps/ecm/src/main.ts` takes 1.44 secs.

| Method  | Time (sec.) |
| ------------- | ------------- |
| tsx cold  | 2.76|
| tsx warm | 1.44|
| makefile cold| 0.8
| makefile warm| 0.3|

**Comment by privatenumber** [comment]
Related: https://github.com/nodejs/node/issues/34049

Hope they find a Node.js solution to this.

**Comment by ulken** [comment]
> Related: [nodejs/node#34049](https://github.com/nodejs/node/issues/34049)
> 
> Hope they find a Node.js solution to this.

Are we there yet? https://github.com/nodejs/node/issues/34049#issuecomment-1752324147

**Comment by privatenumber** [comment]
Since it's implemented in Node.js, I imagine tsx would get it for free

Have you tried Node [v21.1.0](https://github.com/nodejs/node/releases/tag/v21.1.0) or [v21.0.0](https://github.com/nodejs/node/releases/tag/v21.0.0)?

**Comment by ulken** [comment]
I haven't. Missed the part about holding off on back-porting to 20.X.

I'll give it a try and report back.

**Comment by ulken** [comment]
Sorry, I was a little quick reading the issue description here. My use case is not for scripts. It's for running AVA without transpiling TS to JS first. Works fine in 18, but not in 20 (new LTS). Oh, well, sorry for the interruption.
