### ISSUE TITLE
Expiremental message is visible

### ISSUE THREAD

**Issue by polRk** [esbuild-kit/tsx#176]
### Bug description

I use node v19.3.0 and when i use tsx i see an experimental message
```
(node:96559) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
```

### Reproduction

node v19.3

```json
{
  "name": "app",
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "codegen": "ESBK_TSCONFIG_PATH=./tsconfig.scripts.json tsx ./scripts/codegen.ts"
  },
  "dependencies": {
    "tsx": "^3.12.1"
  }
}
```

### Environment

```shell
System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1
    Memory: 96.48 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  npmPackages:
    tsx: ^3.12.1 => 3.12.1
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment]
Reproduction please.

**Comment by polRk** [comment]
Also error in node v18.13.0

**Comment by polRk** [comment]
@privatenumber I can not provide reproduction because it under NDA.

I am using monorepo under pnpm, typescript and top-level await

**Comment by privatenumber** [comment]
I can't help you if I can't reproduce the problem, so this issue won't be productive until then.

You're expected to provide a _minimal_ reproduction. Not an _exact_ reproduction.

Read for details: https://github.com/esbuild-kit/tsx/blob/develop/.github/ISSUE_TEMPLATE/BUG_REPORT.yml
