### ISSUE TITLE
esbuild electron

### ISSUE THREAD

**Issue by mfts2048** [esbuild-kit/tsx#182]
### Feature request

![image](https://user-images.githubusercontent.com/44958959/216770896-4b13bc69-0778-4652-846f-6c5db4b15484.png)

It should be a module, not an exe path.
I'm not sure if there is something wrong with my understanding of esbuild. I think this place should support it

### Why?

Write electron in typescript

**Comment by privatenumber** [comment]
Can you re-file this as a bug?
I'll need to debug a reproduction to help.

**Comment by mfts2048** [comment]
I didn't know how to change the requirement to a bug, so I created a new one.
More happy for you to help
[issue](https://github.com/esbuild-kit/tsx/issues/185)
