### ISSUE TITLE
Run electron with tsx

### ISSUE THREAD

**Issue by mfts2048** [esbuild-kit/tsx#185]
### Bug description

![image](https://user-images.githubusercontent.com/44958959/216805608-059b324c-2eeb-492f-a28e-f4be3607c170.png)

It should be a module, not an exe path.

I'm not sure if there is something wrong with my understanding of esbuild. I think this place should support it

### Reproduction

@privatenumber 

main.ts

```
import { app, BrowserWindow } from "electron";
import electron from "electron";
import path from "node:path";

const createWindow = () => {
	const win = new BrowserWindow({
		width: 800,
		height: 600,
		webPreferences: {
			preload: path.join(__dirname, "preload.js"),
		},
	});

	win.loadFile("index.html");
};

console.log("");
console.log(electron);
console.log("");

app.whenReady().then(() => {
	createWindow();

	app.on("activate", () => {
		if (BrowserWindow.getAllWindows().length === 0) createWindow();
	});
});

app.on("window-all-closed", () => {
	if (process.platform !== "darwin") app.quit();
});
```

### Environment

```shell
Node.js v19.1.0
node v19.1.0
electron 20.3.11
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by mfts2048** [comment]
@privatenumber

**Comment by privatenumber** [comment]
Did you read the instructions for the reproduction?
https://github.com/esbuild-kit/tsx/issues/new?assignees=&labels=bug%2Cpending+triage&template=BUG_REPORT.yml

**Comment by mfts2048** [comment]
https://github.com/mfts2048/turbo-spork.git 
I'm sorry I didn't read it carefully

**Comment by privatenumber** [comment]
@mfts2048 Were you able to resolve the issue?
