### ISSUE TITLE
Does not resolve path aliases starting with "/"

### ISSUE THREAD

**Issue by feraleyebrows** [esbuild-kit/tsx#196]
### Bug description

As the title states, does not resolve path aliases starting with "/". This is problematic as AWS Lambda requires you to import from other layers using "/opt/nodejs/". You therefore cannot use tsx to run or test files locally without either altering the path manually or seeking another solution. 

### Reproduction

https://stackblitz.com/edit/node-ob4hup?file=tsconfig.json

### Environment

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 2.01 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - ~/.asdf/installs/nodejs/18.11.0/bin/node
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
  npmPackages:
    tsx: ^3.12.4 => 3.12.4
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment]
Thanks for the report.

I've confirmed the bug.

Your reproduction has a typo in the directory name though, so TypeScript isn't resolving it: `lambda/layers/seond-layer` -> `lambda/layers/second-layer`
Do you mind fixing it?

<img width="775" alt="Screenshot 2023-03-13 at 7 48 44 AM" src="https://user-images.githubusercontent.com/1075694/224579071-8f16afd3-b6f3-45f6-9e05-660ba6c6b30a.png">

**Comment by feraleyebrows** [comment]
fixed
