### ISSUE TITLE
Watch mode not picking up file changes

### ISSUE THREAD

**Issue by Carnageous** [esbuild-kit/tsx#197]
### Bug description

I am running tsx in watch mode to serve a small API service with Fastify.
When I change any file however, tsx does not re-run. Pressing enter in the shell does work though.

I am using fastify in a pnpm/turbo monorepo, but can reproduce this exact problem with a minmal setup (forked it into the stackblitz below).

Stackblitz picks up file changes so it seems to re-run it. If you cannot reproduce this locally, it's probably something with my setup.

### Reproduction

Stackblitz: https://stackblitz.com/edit/node-cpkbi2?file=index.ts
Repository: https://github.com/Carnageous/tsx-fasitfy-reproduction

### Environment

```shell
System (Tested in WSL Ubuntu 22 and Windows 11):
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz        
    Memory: 12.79 GB / 15.58 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  npmPackages:
    tsx: ^3.12.1 => 3.12.5
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by bobmoff** [comment]
Yeah for me too, it only rebuilds when i change the file that is declared as the argument. Not imported files. 😢

**Comment by Carnageous** [comment]
Now that I tested it, it also works (though on a different compouter then before).
I will test it once again on the first machine and close this issue if it is dependant on the system. It might be a weird windows / WSL mounting thing in my case.

**Comment by bobmoff** [comment]
I think it might have something to do with typescript paths in my case.

i have:
```typescript
 "paths": {
      "@/*": ["./src/*"]
    }
 ```

```typescript
import { Thingy } from '@/thingy'
```
The above does not work. But changing to:
```typescript
import { Thingy } from './thingy'
```
.. makes it work.

**Comment by Carnageous** [comment]
For me the issue seemed to have been the fact that my files were stored on a FAT32 disk shared between Linux and Windows. So probably a Linux issue. Will close this as my problem is fixed by moving to another hard drive.
