### ISSUE TITLE
This package doesn't work with NestJS

### ISSUE THREAD

**Issue by 8NAF** [esbuild-kit/tsx#199]
### Bug description

I am using this package to compile my `NestJS` project. The compilation process is successful, but when running the application, it throws an error.
I'm not sure if this issue is caused by `NestJS` or `tsx`, so I tried compiling my project with `ts-node` and `tsc`, and everything worked fine. That's why I decided to create the issue here.

### Reproduction

This is the [reproduction](https://stackblitz.com/edit/node-l4d5md).

Run the `start:tsx` script and access `localhost:3000`, the terminal will log an error: `Cannot read properties of undefined (reading 'get')`.
You can run the `start:ts-node` or `start:tsc` script and access `localhost:3000` to see that the application does not have any errors.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
    Memory: 1.10 GB / 7.84 GB
  Binaries:
    Node: 19.7.0 - ~\AppData\Local\fnm_multishells\13768_1678794319159\node.EXE
    npm: 9.5.0 - ~\AppData\Local\fnm_multishells\13768_1678794319159\npm.CMD   
  npmPackages:
    tsx: ^3.12.5 => 3.12.5
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment]
I haven't looked into it extensively, but it looks like your code is using decorators.

esbuild doesn't support decorators:
- https://github.com/esbuild-kit/tsx#does-it-have-any-limitations
- https://esbuild.github.io/content-types/#no-type-system

**Comment by 8NAF** [comment]
The issue has been resolved [here](https://github.com/dividab/tsconfig-paths/issues/243#issuecomment-1468660852)

**Comment by 8NAF** [comment]
- [ ]

**Comment by privatenumber** [comment]
Nice, thanks for sharing the workaround!
