### ISSUE TITLE
REPL import statement support

### ISSUE THREAD

**Issue by loynoir** [esbuild-kit/tsx#213]
### Feature request

REPL import statement support

### Why?

- deno REPL support import statement
- node typescript REPL support typescript import statement would be convenient and elegant.

### Alternatives

Rewrite
```ts
import {foo} from "bar"
```
To
```js
var {foo} = await import("bar")
```

### Additional context

https://github.com/esbuild-kit/tsx/issues/52

**Comment by privatenumber** [comment]
tsx is not interested in Deno compatibility. tsx is interested in adding TypeScript support in Node, but this has nothing to do with it.

While I agree this would be a nice feature, this should be a feature request for Node.js.

**Comment by coreyward** [comment]
I'm not sure if alignment with ts-node is at all desired, but this is something that it supports with the right configuration.

**Comment by privatenumber** [comment]
Why dont you open a feature request with Node?

**Comment by coreyward** [comment]
@privatenumber Just sharing some context. No need to get upset at me.

**Comment by privatenumber** [comment]
? Im not upset. Genuine question.

I really think this feature request should be filed with Node since it's an obvious DX improvement.

**Comment by loynoir** [comment]
I did already filed with Node.

 https://github.com/nodejs/node/issues/47278

But think in another way, tsx do AST transform, while node consider not.

So, maybe easier to implement such feature during AST transform.

**Comment by privatenumber** [comment]
That's cool, thanks for sharing!

However, tsx is a TypeScript & ESM enhancement, and not a place to just add arbitrary Node improvements.

I would keep pushing it in Node as that's where it belongs. Try tagging stake holders and get more people involved.

Alternatively, you can start a separate project to enhance Node.
