### ISSUE TITLE
Expose esbuild `loader` option

### ISSUE THREAD

**Issue by jack828** [esbuild-kit/tsx#22]
Hi,

Thanks for the great library. I'm in the process of migrating entirely away from babel (if i can do it!) and I'd like to use this as my transpiling runtime.

However, I have some feature differences between the development mode (using tsx) and in production (using transpiled files).

Esbuild supports a loader syntax:
```
  --loader:X=L          Use loader L to load file extension X, where L is
                        one of: js | jsx | ts | tsx | css | json | text |
                        base64 | file | dataurl | binary
                        
```

However tsx does not, so when i have a file that requires something I will treat as a string such as `const template = require('./email-template.tpl')`, tsx errors out.

I believe I am using both tools correctly, but happy to provide more information on the usage.

**Comment by hyrious** [comment]
The loader option as a record is only supported in build mode. However as I know `tsx` is working using the transform mode of esbuild. We may have to simulate that manually.

**Comment by privatenumber** [comment]
Yep. tsx just spins up Node.js with [this loader](https://github.com/esbuild-kit/tsx/blob/3e81d19bf759b512eb74360861f5abeb9d638ef0/src/run.ts#L38) to teach it how to handle TypeScript files.

The run-time is still Node, so you should simply add another loader to teach Node.js how to handle `.tpl` files and pass it in.

If Node.js allows multiple loaders, you can do this:
```sh
tsx --loader ./tpl-loader.js ./file.ts
```

If not, feel free to open a feature request for it.
