### ISSUE TITLE
failed to import `.mts` file without extension in `.mjs` file

### ISSUE THREAD

**Issue by trim21** [esbuild-kit/tsx#222]
### Bug description

app.mjs

```js
import { v } from "./lib"
console.log(v)
```

lib.mts

```ts
export const v = "hello"
```

```bash
npx tsx app.mjs
```

```text
Cannot find module '.../lib' imported from .../app.mjs
```

### Reproduction

https://github.com/trim21/node-4wre7g/tree/main

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 11.49 GB / 31.93 GB
  Binaries:
    Node: 18.15.0 - ~\scoop\apps\nodejs-lts\current\node.EXE
    Yarn: 1.22.19 - ~\scoop\apps\nodejs-lts\current\bin\yarn.CMD
    npm: 9.6.2 - ~\scoop\apps\nodejs-lts\current\bin\npm.CMD
  npmPackages:
    tsx: ^3.12.1 => 3.12.6
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment]
I don't think this is a bug.

Your `tsconfig.json` is missing an `allowJs`, but even with it, it will compile the files `app.mjs` -> `app.mjs`, and `lib.mts` -> `lib.mjs`. And Node.js wouldn't be able to resolve `./lib` to `./lib.mjs`.

**Comment by trim21** [comment]
that make sense.
