### ISSUE TITLE
Add the possibility to configure the loader to use for esbuild

### ISSUE THREAD

**Issue by fbonin** [esbuild-kit/tsx#225]
### Feature request

It seems that the loader for esbuild is hardcoded to "ts" in the code : 

```
const transformed = await transform(
	code,
	filename,
	{
		loader: 'ts',
		tsconfigRaw: {
			compilerOptions: {
				preserveValueImports: true,
			},
		},
		define: {
			require: 'global.require',
		},
	},
);
```

Would it be possible to make it configurable so that we can load other files (for example loader:.txt=file)

### Why?

I would like to be able to import other kind of files and it is possible to do with esbuild but not with tsx

### Alternatives

I did not find any alternative

**Comment by fbonin** [comment]
I just want to pass the info to esbuild as it is possible to do that in esbuild using loaders.

**Comment by privatenumber** [comment]
I'm not sure if I explained it clearly, but tsx is a TypeScript runtime that runs on top of Node.js. esbuild is used to transform TS to JS, but that's about it—you shouldn't expect any other similarities. It's not an esbuild runtime, and esbuild is not used to handle resolutions (e.g. `.txt` files).

That being said, support for loading `.txt` will not be added because it's not supported in TypeScript. It's trivial to write a loader for `.txt` files so I recommend doing that instead. Let me know if you have any further questions!

**Comment by fbonin** [comment]
Hi,
From my understanding, tsx uses esbuild to transpile the Typescript into JavaScript and then uses Node to run the result. 

I would like to have the possibility to pass parameters to the esbuild transform API before it is run by node and right now it is not possible to do so. 

The .txt example is just and example as I would like to be able to configure the loader used by esbuild here https://esbuild.github.io/api/#loader. 

Sorry if I was not clear earlier. 

Regards

**Comment by fbonin** [comment]
Hi,
I just want to add that it is possible to import txt file (or other type of files) in typescript using this approach 

https://stackoverflow.com/questions/56175900/how-do-you-import-a-text-file-into-typescript

Thus the fact that you can't configure the esloader blocks this capability. 

Regards

**Comment by fbonin** [comment]
This is an example with webpack but you can do the same thing with esbuild loader. Basically typescript will let you do this but you need to have a loader configured properly and esbuild allows this here :  

https://esbuild.github.io/content-types/

I have a project that uses esbuild and then run node after the transpilation and it just works. 

The problem with tsx is that it does not allow the configuration of the loader of esbuild.

**Comment by fbonin** [comment]
As an example, using this command : 

```
esbuild src/index.ts --bundle --sourcemap --outdir=dist --platform=node **--loader:.yaml=file** 
```

esbuild will generate these files : 

![image](https://user-images.githubusercontent.com/732394/234348631-62c04de5-60b6-4a61-9820-8df6a6db0341.png)

If you created a file like this in Typescript : 

![image](https://user-images.githubusercontent.com/732394/234349257-55ae0d6c-c1cc-4129-9453-00cf68934df2.png)

You will then have the possibility to load the file directly from the dist folder of esbuild instead of having to copy and paste it in a different step. 

![image](https://user-images.githubusercontent.com/732394/234349546-623ab722-de4e-462e-9857-f2335218cdfa.png)

I know I could manage this in another step and then copy these files without using esbuild but it makes it easier to do it this way in my CICD pipeline. I was to use tsx to run locally but it does not allow me to configure the esbuild loader and thus cannot be used.

I hope it is clearer.

Regards

**Comment by fbonin** [comment]
hi, I read more about the transform API and now I understand that it is not aware of the file system (only one string) and thus can't support the feature above (it only works with the `build` api)

**Comment by privatenumber** [comment]
Regardless of the capabilities of the Transform API, it simply doesn't fit into the scope of tsx.

But considering this is super easy to do on your own (3 lines of code), I encourage you to just make it yourself.
