### ISSUE TITLE
conflicts with fix-esm

### ISSUE THREAD

**Issue by scjmjy** [esbuild-kit/tsx#230]
### Bug description

`tsx` conflicts with `fix-esm`

### Prepare test code:
```ts
// test.ts
import "@koa/multer";
// ↑↑↑ TypeError
```

### Run with `tsx`
```bash
tsx test.ts
```

### Got a TypeError
```bash
/node_modules/fix-esm/index.js:40
                Module._extensions[".mjs"] = newLoader;
                                         ^
TypeError: Cannot assign to read only property '.mjs' of object '[object Object]'
```

![image](https://user-images.githubusercontent.com/3145541/235229781-252ef33c-2aa5-4ed6-b064-15747a05f540.png)

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 4.80 GB / 7.73 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment]
The error is coming from `fix-esm` because it's trying to override tsx's loader, which would negate using tsx. That's to say this is expected behavior and you should use them separately.

I just looked up [fix-esm](https://git.cryto.net/joepie91/fix-esm.git). Doesn't tsx address the same problem? Why are you using them together?

**Comment by scjmjy** [comment]
Thanks for your reply.

I'm not using `fix-esm` **directly**.
 `fix-esm` is a dependency of `"@koa/multer"`.
 And I'm using `"@koa/multer"`.🙂

**Comment by privatenumber** [comment]
Sounds like the best place to file an issue.
