### ISSUE TITLE
ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language

### ISSUE THREAD

**Issue by zaripych** [esbuild-kit/tsx#236]
### Bug description

When I run `tsx code.ts` I get following output:
```sh
➜  esm-loader-warning-repro pnpm tsx code.ts
(node:76711) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
Hello esm-loader-warning-repro!
```

I expected:
```sh
Hello esm-loader-warning-repro!
```

I've noticed that we already suppress some warnings [in here](https://github.com/esbuild-kit/tsx/blob/develop/src/suppress-warnings.cts)

Should we suppress this type of warning as well?

### Reproduction

I have `"type": "module"` in my `package.json`:
```json
{
  "name": "esm-loader-warning-repro",
  "version": "1.0.0",
  "type": "module",
  "dependencies": {
    "tsx": "^3.12.7"
  }
}
```
`code.ts` has following content:
```ts
import pack from "./package.json";

console.log(`Hello ${pack.name}!`);
```
I'm using Node 18:
```sh
➜  esm-loader-warning-repro pnpm tsx --version
tsx v3.12.7
node v18.16.0
```

### Environment

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 24.08 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  npmPackages:
    tsx: ^3.12.7 => 3.12.7
```

### Can you work on a fix?

- [X] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment]
IIRC they have a new way of making import assertions. Could we use that instead on newer versions of Node.js?

**Comment by zaripych** [comment]
In my example above, I do not do any assertions explicitly, it's the latest version of the `esm-loader` that causes the warning.

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/396623/236368464-5ad9ee89-b7fe-4cf4-a855-a86482f8b3d8.png">

If we can do something to make the warning go away in the `esm-loader` then we can take that path. I'm not very familiar with loader API, but ignoring a warning by adding a string to an array seems like an easy fix with low risk.

**Comment by ArnaudBarre** [comment]
I've been annoyed by this warning so I tried to build a slim tsx version. For the JSON import [I provided a loader](https://github.com/ArnaudBarre/tnode/blob/32000f2172f1dea28e5f1d43914480507ad78b86/loader.js#L16-L19) to that there is not warning not usage of experimental API:

**Comment by privatenumber** [comment]
The warning was added in https://github.com/nodejs/node/pull/46901 and motivated by https://github.com/nodejs/node/issues/46830 but there is currently no successor to the `assert` syntax.
