### ISSUE TITLE
Can't install tsx with pnpm

### ISSUE THREAD

**Issue by darwinva97** [esbuild-kit/tsx#243]
### Bug description

```
pnpm init
pnpm add -D tsx
```

After executing these steps the following is displayed:

![image](https://github.com/esbuild-kit/tsx/assets/30082909/e1238148-898a-49c2-907b-12947863361d)

![image](https://github.com/esbuild-kit/tsx/assets/30082909/7d271212-edf4-4935-852a-63cac1397b02)

It appears in the .pnpm folder inside node_modules but not as a binary nor in package.json

### Reproduction

_In this case it doesn't make sense to upload a repository because it can't be reproduced from one (since it can't be installed in the package.json) but by following the steps above._

### Environment

```shell
System:
    OS: Linux 6.3 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz
    Memory: 7.60 GB / 11.55 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.13.0 - ~/.volta/tools/image/node/18.13.0/bin/node
    Yarn: 4.0.0-rc.36 - ~/.volta/tools/image/yarn/4.0.0-rc.36/bin/yarn
    npm: 8.19.3 - ~/.volta/tools/image/node/18.13.0/bin/npm
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by so1ve** [comment]
Could you copy your terminal log?

**Comment by darwinva97** [comment]
> Could you copy your terminal log?

I already updated the issue with the logs

**Comment by so1ve** [comment]
It seems that the install step is not completed.

**Comment by privatenumber** [comment]
Installing tsx with pnpm works for me.

Closing as this seems un-actionable (no repro, or even an error message). Happy to re-open once there's more information that further indicates something can be improved in tsx.

You might want to consider that it may be a pnpm issue, or your environment. Try installing with npm—if it works, it's likely a pnpm issue than a tsx one.
