### ISSUE TITLE
`watch` mode in `node.js 20` doesn't watch changes in non-entry files

### ISSUE THREAD

**Issue by o-alexandrov** [esbuild-kit/tsx#246]
### Bug description

`watch` mode works on node.js `lts/hydrogen` v18, but doesn't on `20+`.

### Reproduction

1. Create 2 files

```ts
// file-1.ts - this is your entrypoint
import { example } from './file-2';
console.log(example);
```

```ts
// file-2.ts
export const example = 'Hello World!';
```

2. Run `tsx watch file-1.ts`
3. Modify value in `file-2.ts`
4. Observe there's `no rerun` by `tsx`

### Environment

```shell
System:
  OS: MacOS (currently latest 13.3)
  CPU: m1 pro
  Shell: zsh
Binaries:
  Node: 20.1.0
npmPackages:
  tsx: `3.12.7` (current latest)
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by lockieluke** [comment]
+1

**Comment by Billcountry** [comment]
+1

**Comment by marvinroger** [comment]
I think it might be related to a bug in Chokidar, see https://github.com/vitejs/vite/issues/12495

**Comment by o-alexandrov** [comment]
`chokidar` isn't part of the dependencies of `tsx` though.
here's how to confirm, either:
- create a package.json with a single dependency `tsx`, install, and observe the lock file
- or run `npx howfat tsx` to get a report how you see on the img below

<img width="543" alt="Screenshot 2023-05-30 at 10 11 03 AM" src="https://github.com/esbuild-kit/tsx/assets/9992724/83ed2655-9f9a-47ea-8e4f-3fed8b596ffa">

**Comment by marvinroger** [comment]
It's indeed missing from the `package.json`, but it is actually used https://github.com/esbuild-kit/tsx/blob/2a83619ab2b14df0f52a338288520c366a5ebc2f/src/watch/index.ts#L6

That's definitely a bug, if it's working now without `chokidar` being in `dependencies` or `peerDependencies`, it's probably because it's a transitive dependency of another dependency of the project using `tsx`

**Comment by privatenumber** [comment]
chokidar is declared in `package.json#devDependencies` because it's bundled in.

Guessing the bug is upstream. We can either wait for a fix, or migrate to https://github.com/parcel-bundler/watcher.

If anyone is interesting in investigating (here or in chokidar), please feel free to help out.

**Comment by marvinroger** [comment]
My bad, didn't know that.
Out of curiosity, that's quite unconventional and does not allow for deduplication (e.g. another module probably uses `chokidar`, so chokidar would exist twice, the one bundled with `tsx` and the `node_modules` one), what's the purpose of bundling dependencies in the context of Node?

**Comment by privatenumber** [comment]
For tsx, to optimize installation speed when using `npx`.
Explained more here: https://github.com/privatenumber/pkgroll#why-bundle-nodejs-packages

**Comment by Billcountry** [comment]
Found a temporary solution by using tsx as a loader instead:

```sh
node --watch --loader=tsx index.ts
```

**Comment by privatenumber** [comment]
If anyone is able to, please investigate what's causing this.

If it's chokidar, is there an issue tracked in their repository? We can consider swapping to a different watcher.

**Comment by azhar1038** [comment]
I am using Node 20 in Windows and it seems to be working fine.
Is it just a MacOS issue?
Can anyone check if [@parcel/watcher](https://www.npmjs.com/package/@parcel/watcher) is working in mac or not?

**Comment by MKoreo** [comment]
Experiencing identical issues on Linux.
```bash
thopop@Latitude5490: ~ $ uname -r
6.4.1-zen2-1-zen
thopop@Latitude5490: ~ $ node -v
v20.3.1
```

> Found a temporary solution by using tsx as a loader instead:
> 
> ```shell
> node --watch --loader=tsx index.ts
> ```
I don't know why that works for you, but not using tsx directly gives me following error:
```shell
> tsc --build && dotenv -e .env.dev node --watch --loader=tsx src/server.ts --inspect=0.0.0.0:%SERVER_PORT%
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /usr/src/app/projects/backend/auth-service/src/server.ts
```

**Comment by privatenumber** [comment]
Wow thank you so much for the insightful investigation @fspoettel 
I think we can work on a fix now

**Comment by npdev453** [comment]
Wrote a fix https://github.com/esbuild-kit/esm-loader/pull/64 based on @fspoettel research. Working well for me, but can somebody test it in him configurations also too?
 
 @privatenumber, waiting for review.

**Comment by singh-inder** [comment]
Hi, any update on this? I'm using nodejs v20.5.1 and have to restart the server manually when using imports
