### ISSUE TITLE
tsconfig.json "path" doesn't work correctly when starting with "/"

### ISSUE THREAD

**Issue by ViktorQvarfordt** [esbuild-kit/tsx#251]
### Bug description

tsconfig.json "path" doesn't work correctly when starting with "/". It gives an error like this:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/server/foo' imported from /path/to/repo/server/src/foo.ts
```

### Reproduction

**tsconfig.json**
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "/server/*": ["./src/*"]
    }
  },
  "include": ["src"]
}
```

**src/server.ts**
```
import { foo } from '/server/foo'
```

### Environment

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 10.67 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  npmPackages:
    tsx: ^3.12.7 => 3.12.7
```

### Can you work on a fix?

- [X] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment]
Can you provide a reproduction on StackBlitz?

Absolute paths is working in this get-tsconfig test:
https://github.com/privatenumber/get-tsconfig/blob/ea1b356b8abbaef37c167669db89a47113fd6f3c/tests/specs/create-paths-matcher.ts#L358-L381

**Comment by tommy-mitchell** [comment]
I have a similar issue: [minimal reproduction](https://github.com/tommy-mitchell/tsx-repro)

My project has separate `tsconfig.json` files for source and test files. When setting up the `paths` compiler option, my IntelliSense correctly provides type information for imports, but `tsx` fails with the `ERR_MODULE_NOT_FOUND` error:

```ts
// src/index.ts
export const foo = () => "bar";
```

```ts
// src/types.ts
export type Foo = "bar";
```

```ts
// test/test.ts
import assert from "node:assert";
import { foo } from "~/index.ts"; // Errors here
import type { Foo } from "~/types.ts";

assert.strictEqual(foo() as Foo, "bar");
```

**Comment by privatenumber** [comment]
@tommy-mitchell 
If it's not the same issue, please start your own thread.

**Comment by privatenumber** [comment]
Will still use the repro as reference but will closing this in favor of https://github.com/esbuild-kit/tsx/issues/196 for tracking purposes. Hope to tackle soon.
