### ISSUE TITLE
bug: tsx is inadvertently adding support for loading .txt file

### ISSUE THREAD

**Issue by privatenumber** [esbuild-kit/tsx#256]
### Discussed in https://github.com/esbuild-kit/tsx/discussions/255

<div type='discussions-op-text'>

<sup>Originally posted by **phbernard** June 13, 2023</sup>
tsx handles text file import out of the box:

```
import myTextFile from 'myTextFile.txt'
```

Is it possible to do the same with binary files? For example:

```
import myBinaryFile from 'myBinaryFile.bin' // DOESN'T WORK
```

A command line option? Using a particular extension maybe?</div>

**Comment by rentalhost** [comment]
I believe that it is supposed to be supported according to the documentation at https://esbuild.github.io/content-types/#text (if I am not mistaken).

Additionally, binary content could also be supported as mentioned in the documentation at https://esbuild.github.io/content-types/#binary.

**Comment by privatenumber** [comment]
Neither. tsx's goal is TypeScript parity, not esbuild parity.

**Comment by privatenumber** [comment]
Fixed via https://github.com/esbuild-kit/cjs-loader/pull/40
