### ISSUE TITLE
Debug Sourcemap support

### ISSUE THREAD

**Issue by upupming** [esbuild-kit/tsx#260]
### Feature request

When run `tsx xxx.ts` in a JavaScript Debug Terminal, breakpoints will not working and the `debugger` will be paused but it is in a compiled (and minified) file, not in the source ts file. Can we map to the original source ts file?

It is paused in a compiled file:

<img width="689" alt="image" src="https://github.com/esbuild-kit/tsx/assets/24741764/9726d818-3dad-4466-b59e-03309efbfaa4">

Expectation is to pause at the original TS file.

### Why?

For better debugging experience.

**Comment by Dimava** [comment]
@upupming try using `inlineSourceMap` or even `inlineSources` so the generated file can sourcemap back to TS code

**Comment by Dimava** [comment]
(Tho I think that should be documented. I also had the same problem)

**Comment by upupming** [comment]
@Dimava Did you mean the config in `tsconfig.json`? I set both `inlineSourceMap` and `inlineSources` to `true`, but it still will break in the compiled file.

**Comment by upupming** [comment]
I tried to change Node version from 12 to 14, it works now. It seems the lower version does not support sourcemap very well.
