### ISSUE TITLE
`npx tsx` not working

### ISSUE THREAD

**Issue by y-nk** [esbuild-kit/tsx#261]
### Bug description

run: `npx tsx` in a brand new terminal. it returns `command not found`. other packages are ok tho.

<img width="682" alt="image" src="https://github.com/esbuild-kit/tsx/assets/411625/17e0f8a0-5036-4783-8456-fbb627b6d812">

### Reproduction

it's a npx related thing, there's no really other reproduction step than `npx tsx`. i'm happy to provide more information and test things.

### Environment

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 149.28 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/Library/Caches/fnm_multishells/58563_1688712541386/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/58563_1688712541386/bin/npm
    pnpm: 7.24.3 - /opt/homebrew/bin/pnpm
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment]
The reproduction should be a StackBlitz demo or some clean slate environment showing it doesn't work.

Does it work on StackBlitz or any other environment? If so, I'm thinking this is an issue with your environment.

In any case, this sounds like a npx issue at the very least. I'm closing this as there isn't enough information to say this is a tsx bug, but I'm happy to help debug or re-open when there's more info.

What does `which tsx` output?
