### ISSUE TITLE
tsx breaks importing paths that include query params

### ISSUE THREAD

**Issue by iambumblehead** [esbuild-kit/tsx#264]
### Bug description

The following test fails when tsx is used as the loader
```javascript
import test from 'ava'
import assert from 'assert'

test('tsx should not break when import paths include query params', async () => {
  assert.ok(await import('../local/main.ts?query=params'))
})
```
**actual result:** The test fails
```bash
  TypeError {
    code: 'ERR_UNKNOWN_FILE_EXTENSION',
    message: 'Unknown file extension ".ts" for /home/bumble/tsx-demo/tests/local/main.ts',
```

**expected result:** The test should not fail.

### Reproduction

```javascript
import test from 'node:test'
import assert from 'assert'

test('tsx should not break when import paths include query params', async () => {
  assert.ok(await import('../local/main.ts?query=params'))
})
```

### Environment

```shell
System:
    OS: Linux 6.3 Arch Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 18.43 GB / 31.07 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.4.0 - /usr/bin/node
    npm: 9.8.0 - /usr/bin/npm
  npmPackages:
    tsx: ^3.12.7 => 3.12.7
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by qodesmith** [comment]
@iambumblehead I've never seen query params on a file location. Is that valid? What's that used for?

**Comment by iambumblehead** [comment]
@qodesmith to unit-test mock an esm-imported-module; inside the main thread, `import('../local/main.ts?mock=1')`, then inside a --loader, `if (loadedFileURLQueryMock) return loadedModuleMocks[loadedFileURLQueryMock]`

**Comment by iambumblehead** [comment]
@qodesmith https://github.com/iambumblehead/esmock/issues/209

**Comment by privatenumber** [comment]
@qodesmith 

To determine if it's valid, simply check if it works on Node.js or TypeScript.
