### ISSUE TITLE
Unable to debug imported variables under VSCode debugger 

### ISSUE THREAD

**Issue by npdev453** [esbuild-kit/tsx#270]
### Bug description

I aslo try:
* different configuration of sourceMap flags and etc in launch and tsconfig
* different versions of nodejs (16, 18, 20)    

but it does not matter.

Seems like in runtime code `debugMe` will be looks like `import_importMe.debugMe` but sourceMap not refect that.

![image](https://github.com/esbuild-kit/tsx/assets/1401931/84c272fa-86b2-48b9-8d61-9366aaf7aaa9)

### Reproduction

index.ts
```
import {debugMe} from './importMe'

console.log(debugMe);
```

importMe.ts
```
export const debugMe = Math.random();
```

### Environment

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: Inter
    Memory: 2.27 GB / 3.84 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.20.1 - /usr/bin/node
    npm: 8.19.4 - /usr/bin/npm
    pnpm: 8.6.6 - ~/.local/share/pnpm/pnpm
  npmPackages:
    tsx: ^3.12.7 => 3.12.7
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by npdev453** [comment]
@privatenumber 
could you please show related task? And also please add it to roadmap

**Comment by privatenumber** [comment]
Away from computer now but try searching, there's a few IIRC.

Also, search the roadmap. It should already be on it.

**Comment by npdev453** [comment]
> Away from computer now but try searching, there's a few IIRC.
> 
> Also, search the roadmap. It should already be on it.

Mmm, double checked it again, maybe you know issue that indirectly related to that problem that I cant see.
I see some issues about imports and 'paths' or something, but seems like that absolutly not equal with that problem.

Also in Roadmap in section 'Debugging' is empty (mean nothing about that).

**Comment by privatenumber** [comment]
It's a debugger limitation, not tsx's limitation:
https://github.com/esbuild-kit/tsx/issues/98#issuecomment-1254625677

I don't think this is always possible to map, but you can open an issue with VSCode or Chromium.

**Comment by npdev453** [comment]
Seems like vscode-js-debugger has some improved `names` recognition
https://github.com/microsoft/vscode-js-debug/issues/1383

Also I find that `tsc` doest emit names for sourceMaps (for last 7 years) and after some tests iw got the same behavior.
https://github.com/microsoft/TypeScript/issues/9627

__
I will leave this information for those who want to dive into extended debugging starting from tsx
