### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by putao520** [esbuild-kit/tsx#275]
### Bug description

Code: 
```
userConfigModule = await import((0, _url.pathToFileURL)(path).href);
```
will be translated to
```
 (0, _url.pathToFileURL)(path).then
```

### Reproduction

if (process.env.__NEXT_TEST_MODE === "jest") {
    // dynamic import does not currently work inside of vm which
    // jest relies on so we fall back to require for this case
    // https://github.com/nodejs/node/issues/35889
    userConfigModule = require(path);
} else {
    userConfigModule = await import((0, _url.pathToFileURL)(path).href);   // here
}
const newEnv = {};

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz
    Memory: 98.72 GB / 127.92 GB
  Binaries:
    Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.27.1 - ~\AppData\Roaming\npm\pnpm.CMD
  npmPackages:
    tsx: ^3.12.7 => 3.12.7
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment]
Filed a bug in es-module-lexer:
https://github.com/guybedford/es-module-lexer/issues/156

**Comment by privatenumber** [comment]
Closing in favor of https://github.com/esbuild-kit/tsx/issues/192
