### ISSUE TITLE
Cannot import from file symlinked from outside package.json dir when using "type": "module"

### ISSUE THREAD

**Issue by samal-rasmussen** [esbuild-kit/tsx#286]
### Problem

I have made a git repo with the reproduction:
https://github.com/samal-rasmussen/tsx-symlink-import-reproduction

You see this folder structure:
broken/
├─ index.ts
├─ package.json
├─ <symlink to ../watman.ts>
works/
├─ index.ts
├─ package.json
├─ <symlink to ../watman.ts>
watman.ts

`index.ts` just imports from `./watman`.

`broken` has `"type": "module"` in `package.json` while `works` does not. This is the only difference between the two.

In both broken and works I run: `npx tsx index.ts`

Inside the `broken` dir I unfortunately get this error:
```
broken % npx tsx index.ts 
<snip>/tsx-symlink-import-reproduction/broken/index.ts:1
import { watman } from "./watman";
         ^

SyntaxError: The requested module './watman' does not provide an export named 'watman'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

Node.js v18.17.1
```

### Expected behavior

Import of `watman` works in both `broken` and `works` folder.

### URL

https://github.com/samal-rasmussen/tsx-symlink-import-reproduction

### Version

v3.12.7

### Node.js version

v18.17.1

### Package manager

npm

### Operating system

macOS

### It would be amazing if you can contribute to the project!

- [ ] I plan to open a pull request for this issue.

**Comment by samal-rasmussen** [comment]
And five minutes after going to all the effort of making this high quality bug report I find:
https://nodejs.org/api/cli.html#--preserve-symlinks

Et voilà!
```
broken % npx tsx --preserve-symlinks index.ts
watman
```

**Comment by privatenumber** [comment]
Thanks for filing it :)

Part of the intention of the issue template is to set up reporters to successfully debug their own problem.

The great thing about creating a minimal reproduction is it's half the debugging process.

I'm sure creating it and talking about it helped you find your solution.
