### ISSUE TITLE
can I stop minification, it fracks up debugging

### ISSUE THREAD

**Issue by jacobbogers** [esbuild-kit/tsx#288]
### Problem

I cannot debug into normal non minified code from node_modules

### Expected behavior

dont minify, look at screenshot, its unreadable code

![image](https://github.com/esbuild-kit/tsx/assets/896018/6422b6fe-3d13-40f9-ac4b-4708b87d545b)

### Minimal reproduction URL

https://stackblitz.com/edit/node-pwjhc5?file=tsconfig.json

### Version

9.5.0

### Node.js version

18.15.0

### Package manager

npm

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Not a bug. Explanation here: https://github.com/esbuild-kit/core-utils/blob/bdf4ef3d701288fbf8cda6f3564b61fe86defcd0/src/transform/get-esbuild-options.ts#L18

In the future, `node_modules` won't be transformed so you'll be able to debug non-minified code. However, you should just setup sourcemaps so you can debug it.
