### ISSUE TITLE
pnpm failed to install tsx

### ISSUE THREAD

**Issue by lovelyyl** [esbuild-kit/tsx#29]
ENOENT  ENOENT: no such file or directory, copyfile '/Users/shuiluo/Library/pnpm/store/v3/files/35/760ee16f278b22518ce1ba0b25715f07b3fdfe4bfebc6e2002edd360f74932d6e4b24e9184bcaf3762f621f0accb1cc44c0b3752d6c254b8af213f71276359-exec' -> '/Users/shuiluo/Documents/vite3-react-next/node_modules/.pnpm/registry.npmmirror.com+esbuild@0.14.38/node_modules/_tmp_970_9cb6b07e2d9d0b10176a126bde7a8a35/node_modules/.bin/esbuild'

Only this dependency is problematic

It is OK to install esbuild separately

pnpm 7.1.8

node 16

**Comment by privatenumber** [comment]
Closing as it doesn't sound like a tsx problem... `tsx` isn't even mentioned in the error

Maybe try it again, or in a separate project, or try clearing the pnpm store (`~/Library/pnpm/store`). If still problematic, ask in the pnpm repo.
