### ISSUE TITLE
Wrong line numbers in stack traces when using Node v20

### ISSUE THREAD

**Issue by thesmart** [esbuild-kit/tsx#291]
### Problem

I was writing a unit test, and noticed that stack traces have the wrong line numbers when using Node v20:

Switch to Node v20, run the test:
```
$ nvm use 20
$ node --loader tsx --no-warnings --test index.test.ts
  Error: is the line number right?
      at SomeLib.doSomething (file:///Users/smart/thesmart/repro-tsx-line-no/lib.ts:1:149)
      at TestContext.<anonymous> (file:///Users/smart/thesmart/repro-tsx-line-no/index.test.ts:1:121)
```

Switch to node v18, run the test:
 ```
 $ nvm use 18
 $ node --loader tsx --no-warnings --test index.test.ts
  Error: is the line number right?
      at SomeLib.doSomething (/Users/smart/thesmart/repro-tsx-line-no/lib.ts:3:11)
      at TestContext.<anonymous> (/Users/smart/thesmart/repro-tsx-line-no/index.test.ts:7:5)
 ```

The line numbers in v20 are wrong.

### Expected behavior

I would expected Node v20 to work the same as Node v18 and to have the correct line numbers to match where the exception was thrown.

### Minimal reproduction URL

https://github.com/thesmart/repro-tsx-line-no

### Version

v3.12.7

### Node.js version

v20.5.1

### Package manager

yarn

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
tsx hasn't changed, so sounds like a regression in Node.js? Can you file a bug report there?

FYI the reproduction can be more minimal because it's specifically related to how Node.js handles source maps—unrelated to the test runner or TypeScript.

**Comment by privatenumber** [comment]
Filed an issue in Node.js: https://github.com/nodejs/node/issues/49455

**Comment by privatenumber** [comment]
Should be fixed now. Get the update with `npm update @esbuild-kit/esm-loader`

**Comment by mbrevda** [comment]
wow, this was just a tiny bug but it makes such a big difference to the dev experience. Thanks for fixing!

**Comment by neelance** [comment]
It seems like this regressed with v3.14.0. Using Node.js 20 the line numbers look right with v3.13.0 but not with v3.14.0 any more.

**Comment by neelance** [comment]
@privatenumber Could you please reopen this issue or should I open a new one?

**Comment by privatenumber** [comment]
Unless the repro above is broken with the latest tsx, can you open a new issue with reproduction?

**Comment by neelance** [comment]
You are right, the repro above seems to be fine with v4.2.0 on Node.js 20. Very similar issue that I'm seeing with our code, though. I'll figure out a new repro and open a new issue.

**Comment by neelance** [comment]
I've filed #404.
