### ISSUE TITLE
Support following `path` alias

### ISSUE THREAD

**Issue by antfu** [esbuild-kit/tsx#3]
https://github.com/antfu/esno/issues/24#issuecomment-1125429806

**Comment by tachibana-shin** [comment]
> [esbuild-kit/esno#24 (comment)](https://github.com/esbuild-kit/esno/issues/24#issuecomment-1125429806)

Can be solved with https://github.com/esbuild-kit/esm-loader/pull/11

**Comment by privatenumber** [comment]
This feature is pretty much complete:
- https://github.com/esbuild-kit/esm-loader/pull/22
- https://github.com/esbuild-kit/cjs-loader/pull/8

I'm looking for help testing it before releasing it in a the next few days.

Please let me know how it works for you:
```sh
npm i 'esbuild-kit/tsx#built/ts-paths'
```

**Comment by laurentpayot** [comment]
@privatenumber It’s working great for me. Thanks! :+1:

**Comment by alexturpin** [comment]
@privatenumber just what I came here looking for and it works beautifully, thank you!

**Comment by semoal** [comment]
Same here, works nicely from my side. Big monorepo with api, workers and front-end  libs ;)
