### ISSUE TITLE
hmr support

### ISSUE THREAD

**Issue by sia-fl** [esbuild-kit/tsx#303]
### Feature request

hmr support in tsx

### Motivations

I really enjoy working with TSX. It always helps me solve many problems when developing APIs. However, I have one pain point. I wish that when I'm developing, I don't have to completely restart my project every time I make a code change. I have a great idea and have already implemented it based on Node v18. The idea is to create a CommonJS (cjs) file because cjs allows us to override the module methods. I can achieve this by listening to the module._load function to determine the file's call hierarchy. This way, when a file updates, only that file and its parent files get updated. Can this feature be added to TSX? I suggest using it like this: `tsx --hot other....`

Please note that the "--hot" option and its specific functionality would depend on the TSX tool or library you're using, as it's not a standard TypeScript feature. You may need to check the documentation of the TSX tool you're working with to see if such a feature exists or if you can implement it using custom scripts or plugins.

### Alternatives

I've already implemented a preview version using Node.js v18. I'm sorry, I can't share the Git repository as a reference, but I would like to convey my ideas through code snippets.

```javascript
let mod = require('node:module');
const { closeAll } = require('./hmr-hook');
let { workerData, parentPort } = require('worker_threads');
let { pathname } = workerData;

// noinspection JSUnresolvedReference
let oldLoad = mod._load;

let loadWatcher = [];
/**
 * @type {{ [filename: string]: string[] }}
 */
let relationModuleFilenames = {};

const aliveFilenames = [];

// _load
mod._load = function (request, parent, isMain) {
  const loaded = oldLoad.call(this, request, parent, isMain);
  if (
    !/node_modules/.test(parent.filename) &&
    !/package\\modmgr\\src\\hmr-proxy.cjs/.test(parent.filename)
  ) {
    const { filename, children } = parent;
    if (!aliveFilenames.includes(filename)) {
      aliveFilenames.push(filename);
    }
    /**
     * @type {string[]}
     */
    const newFilenames = children.map(child => {
      if (!aliveFilenames.includes(child.filename)) {
        aliveFilenames.push(child.filename);
      }
      return child.filename;
    });
    if (!relationModuleFilenames[filename]) {
      relationModuleFilenames[filename] = newFilenames;
    } else {
      /**
       * @type {string[]}
       */
      const oldFilenames = relationModuleFilenames[filename];
      relationModuleFilenames[filename] = [...new Set([...newFilenames, ...oldFilenames])];
    }
    if (loadWatcher.length) {
      loadWatcher.forEach(fn => fn(request, parent, isMain));
    }
  }
  return loaded;
};

const load = () => {
  require(pathname);
};

const clear = filename => {
  // noinspection JSUnresolvedReference
  delete mod._cache[filename];
  delete relationModuleFilenames[filename];
  aliveFilenames.splice(aliveFilenames.indexOf(filename), 1);
  for (const parentFilename in relationModuleFilenames) {
    const developFilenames = relationModuleFilenames[parentFilename];
    if (developFilenames.includes(filename)) {
      clear(parentFilename);
    }
  }
};

const reload = filename => {
  if (/node_modules/.test(filename)) {
    return null;
  }
  closeAll();
  clear(filename);
  load();
};

parentPort.on('message', message => {
  if (message.type === 'stop') {
    process.exit();
  }
  if (message.type === 'change') {
    if (aliveFilenames.includes(message.filename)) {
      reload(message.filename);
    }
  }
});

load();

```

### Contributions

- [X] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Sounds like a general DX issue with Node.js misplaced on tsx. tsx is just a Node.js wrapper.

I recommend you open this feature request with Node.js instead.
