### ISSUE TITLE
tsx executes dependency entrypoint file twice in esm when using nodejs@20.6.0

### ISSUE THREAD

**Issue by oljekechoro** [esbuild-kit/tsx#304]
### Problem

Hi!

I get an error when I launch an esm file which uses nestjs/common via tsx:

<img width="1070" alt="image" src="https://github.com/esbuild-kit/tsx/assets/9638056/8177d6ac-9b73-49b4-92a2-3bafaa778254">

I found that nestjs/common entrypoint file is executed twice (by placing console.logs).
When I use the previous version of Nodejs this file is executed only once.
The problem happens only when the source file is treated as ESM and only in Nodejs@20.6.0.

I made a reproduction.

### Expected behavior

The entrypoint of dependecy is executed only once.

### Minimal reproduction URL

https://github.com/oljekechoro/tsx-node-nestjs-problem

### Version

v3.12.8

### Node.js version

v20.6.0

### Package manager

yarn

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
I haven't had a chance to look into this yet, but it sounds like you're saying it's a regression in Node.

Have you confirmed it's not a Node bug?

**Comment by privatenumber** [comment]
Did you file a Node.js issue?

**Comment by privatenumber** [comment]
If it's a bug introduced then fixed in Node.js, it doesn't sound like there's anything more to do here.
