### ISSUE TITLE
tsx watch does not work in npm script

### ISSUE THREAD

**Issue by pedroaurelli** [esbuild-kit/tsx#311]
### Problem

I´ve try to use tsx to execute my server.ts file. But when i run the script, it doest not work and throws an error for me:
I tried:
- Delete node_modules and install dependencies again
- Uninstall and install tsx package as dev dependecy
- Clear npm cache 

![image](https://github.com/esbuild-kit/tsx/assets/88735972/6232c7b6-5ea7-420d-a4ab-42d53ec87985)

Other point, when i change `src/server.ts` on dev script to other radomness name, its throws the same error in my terminal 

![image](https://github.com/esbuild-kit/tsx/assets/88735972/224759cc-982e-4e9c-813c-b306f3acdf01)

### Expected behavior

Run my server.ts file.
I change tsx to other compiler package and its works perfectly

### Minimal reproduction URL

https://stackblitz.com/github/pedroaurelli/upload-ai-api?file=package.json

### Version

^3.12.9

### Node.js version

v16.13.1

### Package manager

npm

### Operating system

Windows 10

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Your reproduction runs fine for me

**Comment by privatenumber** [comment]
FYI tsx only supports the latest version of each major. Upgrading to v16.20.2 works fine.

Also for future reference, your minimal reproduction should not include a server or prisma as they're not necessary to demonstrate the bug.
