### ISSUE TITLE
import.meta.env undefined

### ISSUE THREAD

**Issue by leovigna** [esbuild-kit/tsx#313]
### Problem

My package.json `type` is set to `module`
I run a script that gets environment variables using `import.meta.env` (as used by Vite and under bundlers that use [import.meta.env](https://iendeavor.github.io/import-meta-env/guide/getting-started/introduction.html#:~:text=Import%2Dmeta%2Denv%20is%20a,to%20the%2012%2Dfactor%20principle.) under the hood.

### Expected behavior

`import.meta.env` should exist and environment variables should be populated in `import.meta.env`

### Minimal reproduction URL

https://stackblitz.com/edit/node-6gfrx4?file=index.ts

### Version

v3,12,7

### Node.js version

v18.15.0

### Package manager

pnpm

### Operating system

Linux

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by leovigna** [comment]
Is this a bug or do I understand `import.meta` framework incorrectly.
Essentially I have a file that is used by the frontend but also runs in NodeJS. Should I do something like 
`import.meta.env?.NODE_ENV ?? process.env.NODE_ENV`

**Comment by privatenumber** [comment]
The goal of tsx is not Vite parity.

There needs to be a Node.js or TypeScript spec for `import.meta.env`.

**Comment by leovigna** [comment]
ok, thanks!
