### ISSUE TITLE
Running any script shows `globalPreload` warning

### ISSUE THREAD

**Issue by octref** [esbuild-kit/tsx#322]
### Problem

```
$ npx tsx --version       
tsx v3.12.7
node v20.7.0

$ npx tsx index.ts
(node:53227) ExperimentalWarning: `globalPreload` is planned for removal in favor of `initialize`. `globalPreload` is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

### Expected behavior

No warning is shown, as the project intends to "Hides experimental feature warnings".

### Minimal reproduction URL

not possible since it doesn't allow latest node version

### Version

v3.12.7

### Node.js version

v20.7.0

### Package manager

npm

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
This was fixed in https://github.com/esbuild-kit/tsx/releases/tag/v3.12.9

**Comment by octref** [comment]
Nice, thank you so much!
