### ISSUE TITLE
--clear-screen=false clears the screen on reload

### ISSUE THREAD

**Issue by Mcbeer** [esbuild-kit/tsx#328]
### Problem

Passing in the --clear-screen=false flag seems to do nothing.
Also, an option to not clear screen on first run would also be lovely (but that's more of a feature request)

(In the reproduction, change the output in the console log, and see the terminal get cleared)

### Expected behavior

Expect the terminal output to stay when code in watched files changes.

### Minimal reproduction URL

https://stackblitz.com/edit/stackblitz-starters-xgyrij?file=index.ts

### Version

v3.13.0

### Node.js version

v18.18.0

### Package manager

npm

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by LeonardoZivieri** [comment]
You can try to use the --clear-screen option before the file.

`npx tsx watch --clear-screen=false index.ts`

**Comment by Mcbeer** [comment]
And here i have tried every single combination, except, of course, the one that works. 

It seems this fixes my issue. I'll try creating a PR to better document the position of the flag in the command.

@LeonardoZivieri Thanks!
