### ISSUE TITLE
Doesn't run with concurrently

### ISSUE THREAD

**Issue by hornta** [esbuild-kit/tsx#335]
### Problem

This doesn't run when run using the concurrently tool. https://www.npmjs.com/package/concurrently

There is also no output.

### Expected behavior

I expect it to work just as good as nodemon works with concurrently.

### Minimal reproduction URL

-

### Version

16.7.2

### Node.js version

18.18.0

### Package manager

npm

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [X] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Can you provide a minimal reproduction? Happy to reopen when provided.

**Comment by hornta** [comment]
I'm working on one at the moment. I need some help before I can finish that. I'm trying to run tsx in watch mode and at the same time setting some environment variables. This is what I'm trying to do but I don't know where to place the `watch`. 

`"cross-env NODE_OPTIONS='--conditions=development --loader=tsx' node src/index.ts"`

**Comment by hornta** [comment]
I tried also using npm-run-all2 but it doesn't work either when it's the second parallel script.
