### ISSUE TITLE
Support resolving `./foo.js` to `./foo.ts`

### ISSUE THREAD

**Issue by gustavopch** [esbuild-kit/tsx#342]
For some reason, to use ESM in TypeScript, to import `./foo.ts` we need to use `import foo from './foo.js'`, so `@esbuild-kit/esm-loader` should support that.

Basically, try resolving `.js` to `.ts` and `.jsx` to `.tsx`.

Related:
- https://github.com/esbuild-kit/tsx/issues/112#issuecomment-1387660627
- https://github.com/esbuild-kit/tsx/issues/135

BTW, consider distributing the library without minification. Minifying just makes it harder to debug locally and use `patch-package` while providing no benefit.

**Comment by privatenumber** [comment]
Closing as a duplicate of https://github.com/esbuild-kit/tsx/issues/112

**Comment by spearmootz** [comment]
i am getting this error. i posted a similar comment on 112.
