### ISSUE TITLE
tsx 3.14.0 failing when transforming decorators

### ISSUE THREAD

**Issue by nubunto** [esbuild-kit/tsx#348]
### Problem

I have code that uses tsx as a loader and is working correctly in tsx 3.12.7, but breaking in tsx 3.14.0 with the following error:

`ERROR: Transforming JavaScript decorators to the configured target environment ("node18.17.1") is not supported yet`

### Expected behavior

tsx is able to transpile .ts files correctly, as it could in 3.12.7

### Minimal reproduction URL

https://stackblitz.com/edit/node-h93fkt?file=package.json,index.ts

### Version

3.14.0

### Node.js version

v18.17.1

### Package manager

pnpm

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
This was a behavioral correction in esbuild.

You need to set [`experimentalDecorators: true`](https://github.com/evanw/esbuild/releases/v0.18.0#:~:text=Using%20experimental%20decorators%20now%20requires%20%22experimentalDecorators%22%3A%20true) in your tsconfig.json.

**Comment by mvantellingen** [comment]
Hi, i'm running into the same issue. I have the experimentalDecorators defined in my tsconfig file but it doesn't seem to be picked up by tsx. Compiling the code via esbuild directly works, so it seems something goes wrong with the integration between tsx and esbuild.

It does work with the following packages

  "esbuild": "0.17.19",
  "tsx": "3.12.7",
  "@esbuild-kit/cjs-loader": "2.4.2",
  "@esbuild-kit/core-utils": "3.1.0",
  "@esbuild-kit/esm-loader": "2.5.5"

**Comment by darcyrush** [comment]
@privatenumber I am coming across the same issue with `node 21.2.0` and `tsx 4.1.2` - in fact it happens in most versions. Attached is a minimal reproduction project. 

I also tried having a `tsconfig.json` in the root dir, but the issue persists. Issue also happens with the `TSX_TSCONFIG_PATH`

[tsx-min-repo.zip](https://github.com/privatenumber/tsx/files/13367385/tsx-min-repo.zip)

Likely I am doing something incorrect with the setup, but my ideal setup is to use `tsx` with `node` via the `--import` flag (and `--test` flag)

**Comment by privatenumber** [comment]
This is a closed issue.

If you have a minimal reproduction for a bug, please open a new issue and link it in a repository instead of a zip file (looks suspicious).
