### ISSUE TITLE
Using the --loader flag in Node >20.6 throws an error

### ISSUE THREAD

**Issue by vpctorr** [esbuild-kit/tsx#349]
### Problem

Using the --loader flag in Node >20.6 throws the following error:

```
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
Error: tsx must be loaded with --import instead of --loader
The --loader flag was deprecated in Node v20.6.0
    at X (file:///Users/victor/Desktop/Dev/quam/node_modules/tsx/dist/esm/index.mjs:1:1920)
```

### Expected behavior

I believe this is expected, however, this is a breaking change that would justify a warning instead of a hard error, otherwise a major version bump.
This change was not mentioned in the [release notes](https://github.com/esbuild-kit/tsx/releases/tag/v3.14.0) either.

### Minimal reproduction URL

https://codesandbox.io/p/sandbox/cool-mountain-5qs5xx

### Version

v3.14.0

### Node.js version

v20.7.0

### Package manager

npm

### Operating system

Linux

### Contributions

- [X] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by nwalters512** [comment]
This new error breaks using `tsx` with Mocha. Previously in versions `<= 3.13.0`, it was possible to have the following in a `.mocharc.json` file:

```json
{
  "loader": "tsx/esm"
}
```

AFAICT, Mocha doesn't have anything that supports using `--import` instead.

**Comment by privatenumber** [comment]
I'm unclear on what you're asking for here.

But if you were asking how to work around it, it says how you can resolve it in the error:
> tsx must be loaded with --import instead of --loader

Also, see the README changes in the release.

If you're asking why it wasn't released as a breaking change, I feel that it was actually in Node and just surfaced through tsx.

For context, Node v20.6.0 deprecated `globalPreload` in favor of `initialize`. So if a loader only exports `globalPreload`, it emits a lot of warnings (unusable). But if `initialize` is exported, it ignores `globalPreload`, but also requires that it's loaded via `--import` for the source maps to work.

That said, it's only a breaking change via the `--loader` flag, not in the `tsx` CLI. And Node.js warns you that it can change any time so I think it's reasonable:

> 	--experimental-loader is an experimental feature. This feature could change at any time
