### ISSUE TITLE
TypeError: Unexpected response from worker: undefined

### ISSUE THREAD

**Issue by s-kris** [esbuild-kit/tsx#35]
I'm using ts-node to run nextjs app ([custom server](https://github.com/vercel/next.js/tree/canary/examples/custom-server-typescript)).

`yarn dev: ts-node --project tsconfig.server.json server/index.ts`

Using `tsx` throws the below error

```
/Users/<path>/node_modules/jest-worker/build/workers/ChildProcessWorker.js:264
        throw new TypeError('Unexpected response from worker: ' + response[0]);
              ^

TypeError: Unexpected response from worker: undefined
    at ChildProcessWorker._onMessage (/Users/<path>/node_modules/jest-worker/build/workers/ChildProcessWorker.js:264:15)
    at ChildProcess.emit (node:events:527:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

p.s: thanks for bringing this :)

**Comment by privatenumber** [comment]
Do you mind providing a minimal reproduction repository?

I'm not sure what exact setup and commands you're running.

Also note, tsx currently doesn't support the `--project` flag.

**Comment by s-kris** [comment]
Sorry, I'm not able replicate the same error on the starter: https://github.com/s-kris/test-tsx-nextjs-custom-server

I will try to add the packages one by one from my main project to this starter to identify which one is causing the issue.
By looks of it, I think, it must be the testing library.

**Comment by privatenumber** [comment]
Thanks.

Will reopen when reproduction is provided.
