### ISSUE TITLE
An alias `'*': ['src/*']` and `import '.'` in `node_modules` resolves `src/index.tsx` unexpectedly

### ISSUE THREAD

**Issue by JounQin** [esbuild-kit/tsx#42]
As title

More detail https://github.com/prettier/plugin-pug/issues/398

**Comment by yi-ge** [comment]
esm-loader support `index` in dir, but it didn't work

**Comment by JounQin** [comment]
Maybe should report to https://github.com/esbuild-kit/esm-loader instead then?

**Comment by privatenumber** [comment]
I tried reproducing this but no luck. Also don't know what command you ran to make tsx read from a prettier plugin.

Can you provide a minimal reproduction repository?

**Comment by JounQin** [comment]
> Also don't know what command you ran to make tsx read from a prettier plugin.

@privatenumber 

I call prettier's API in a script `scripts/run.ts`:

```ts
import prettier from 'prettier'

await prettier.resolveConfig(process.cwd())
```

**Comment by privatenumber** [comment]
Yup, works fine for me.

**Comment by JounQin** [comment]
OK, I will try to create a reproduction then.

**Comment by JounQin** [comment]
@privatenumber 

https://github.com/JounQin/test/tree/tsx

run `yarn && yarn api`

**Comment by privatenumber** [comment]
I'll leave this open till I add a test to prevent this, but should be fixed via https://github.com/privatenumber/get-tsconfig/releases/tag/v4.0.5

Run `npm update` or reinstall tsx.

**Comment by JounQin** [comment]
@privatenumber Thanks, it's working as expected now.
