### ISSUE TITLE
Running `tsx` for Prisma seed command inside Docker container produces no output.

### ISSUE THREAD

**Issue by brandonpittman** [esbuild-kit/tsx#43]
I'm not sure where to begin debugging this. If I use `tsx` for just a test script, it works just fine, but when I tried swapping out `ts-node` in my Prisma seed command, there's no output and the process hangs forever.

**Comment by privatenumber** [comment]
(Not sure what a Prisma seed command is.)

Can you provide a minimal reproduction repository?

**Comment by privatenumber** [comment]
There was a tsconfig resolution bug that I just fixed: https://github.com/privatenumber/get-tsconfig/releases/tag/v4.0.5

It was making Node resolve '.' to the wrong file and was hard to detect.

Perhaps that was the issue.

Please try reinstalling tsx or running 'npm update'.
