### ISSUE TITLE
Add MacOS Support?

### ISSUE THREAD

**Issue by yi-ge** [esbuild-kit/tsx#44]
### Feature request

MacOS is the mainstream development operating system.

### Why?

I use Linux, Windows and MacOS at the same time, according to my different application scenarios. 
Especially looking forward to adding support for MacOS. thanks.

**Comment by privatenumber** [comment]
It supports macOS.

I developed tsx with it.

Does it not work for you?

**Comment by yi-ge** [comment]
A typescript file include top-level `await` an ES module.
In this case, it may break and crash, which is irregular.
The same code works fine in ubuntu、kali and windows.

**Comment by yi-ge** [comment]
But the ts code after build runs fine in MacOS.

```bash
node --no-warnings --experimental-vm-modules --experimental-specifier-resolution=node --experimental-wasm-modules dist/main.js"
```

**Comment by privatenumber** [comment]
Sounds like you're trying to report a bug.

Please follow the Bug report template and provide the necessary info for others to help you.
