### ISSUE TITLE
Top-level await file as ES module crash.

### ISSUE THREAD

**Issue by yi-ge** [esbuild-kit/tsx#45]
### Bug description

A typescript file include top-level `await` an ES module.

In this case, it may break and crash, which is irregular.

The same code works fine in ubuntu、kali and windows.

But the typescript code after build runs fine in MacOS. 

```bash
node --no-warnings --experimental-vm-modules --experimental-specifier-resolution=node --experimental-wasm-modules dist/main.js
```

Use `ts-node` runs fine on MacOS.

### Reproduction

<img width="1242" alt="tsx" src="https://user-images.githubusercontent.com/6657330/175194395-31379f9a-680c-4a85-ad24-04c5aebb0ca0.png">

### Environment

```shell
System:
  OS:MacOS version: 13.0 Beta (22A5266r).
  CPU:M1
  Shell:zsh
Binaries:
  Node: v18.3.0、v18.4.0.
  npm:8.12.1
npmPackages:
  tsx:3.5.0
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by yi-ge** [comment]
The first execution always works fine.

**Comment by privatenumber** [comment]
Can you provide a link to that test repository in the screenshot?

**Comment by yi-ge** [comment]
Make sure you use `"type"="module"`?

**Comment by yi-ge** [comment]
@privatenumber

**Comment by notflip** [comment]
@yi-ge Where do we set this type=module? TSX doesn't use the tsconfig file? or does it?

**Comment by privatenumber** [comment]
`package.json`:
https://nodejs.org/api/packages.html#type
