### ISSUE TITLE
Support automatically loading modules

### ISSUE THREAD

**Issue by stephenh** [esbuild-kit/tsx#48]
### Feature request

I frequently want to run commands/scripts in my project with "some defaults" applied; typically these defaults are a) using ts-node, and b) using some env variables from a `local.env` file.

Historically I've solved this with an extra `run.sh` script that looks something like:

```bash
#!/bin/bash

export $(grep -v '^#' env/local.env | sed 's/\"/\\\"/g' | xargs)

./node_modules/.bin/ts-node "$@" 
```

But it's cumbersome to copy/paste around and kind of crufty in general.

I'd noticed `tsx` would be able to solve my "use ts-node by default" need, which is great, but I'm hoping it could also solve my "using some env variables by default" need, albeit without adding that explicitly to tsx, and maybe instead via some generic config.

I've thought of two ideas, one might be a `.tsxrc` type file that looks like:

```
NODE_OPTIONS=-r myCustomModule
```

Or another is something in package.json:

```
{
  "tsx": {
     "require": "myCustomModule",
     "NODE_OPTIONS: "-r myCustomModule"
  }
}
```

Where `myCustomModule` would be something that could auto-load the `local.env` file / whatever based on my app's specific conventions.

As a disclaimer, I know this is probably out-of-scope to `tsx`'s core "just run TypeScript automatically" mission, but dunno, thought it wouldn't hurt to at least ask to see if you find this use case worth supporting. Thanks!

### Why?

I'm frustrated that there's not an easy way to apply default settings/behavior to the scripts I run in my project.

### Alternatives

I've been using a `run.sh` shell script; happy to learn of better alternatives if there any.

**Comment by privatenumber** [comment]
tsx is designed to align with Node.js' API as much as possible. That said, if it's not supported by Node.js, it likely won't be by tsx.

I would recommend looking for a 3rd party solution or opening the feature request with Node.js.

I wonder if [`dotenv-cli`](https://www.npmjs.com/package/dotenv-cli) would work for you:
```
dotenv tsx ...
```

**Comment by stephenh** [comment]
Sounds good, that makes sense @privatenumber , thanks!
