### ISSUE TITLE
View generated JS to aid in debugging

### ISSUE THREAD

**Issue by x11x** [esbuild-kit/tsx#58]
### Feature request

An option flag or environment variable that causes tsx to print the path to the generated JS code before executing.

### Why?

I would like to be able to view the generated JS code to assist debugging. I know it is cached in $TMPDIR, so tsx could print the path to help finding it.

### Alternatives

Alternatively, an option to dump the generated code straight to stdout/stderr before running.

Or maybe debugging options I have missed?

Or I could just compile my code directly using esbuild/tsc for debugging. But knowing exactly what code tsx is producing is useful, in case the result of using esbuild/tsc is not the same for whatever reason (different version, different config, etc.).

### Additional context

Debugging is difficult due to error stack traces referencing generated JS, not the source. Have I missed something? I have tried enabling sourceMaps in tsconfig but still don't seem to be getting useful error stack traces. (I guess stack traces is a separate issue)
Thank you.

**Comment by privatenumber** [comment]
Thanks for the request.

Using tsx is designed to be as seamless as using Node.js so this will not be accepted.

With any JavaScript dependency, you can go into `node_modules`, (prettify the code if minified,) and your own `console.log`s as necessary to debug.

If stack traces are inaccurate/broken for you, please file a bug.
