### ISSUE TITLE
Ability to pass `exclude` flag to `watch`

### ISSUE THREAD

**Issue by o-alexandrov** [esbuild-kit/tsx#65]
### Feature request

Add ability to pass `exclude` flag to `watch`

### Why?

When `tsx` is used on a script that creates its dependencies, `exclude` option is required to ignore updates from the specified list of files.

### Alternatives

Wrapping `tsx` with `nodemon --exec 'tsx ...'`

**Comment by privatenumber** [comment]
> When `tsx` is used on a script that creates its dependencies, `exclude` option is required to ignore updates from the specified list of files.

Why is an `exclude` feature required? (Seems you simply explained what the `exclude` feature does instead of why you need it.)

**Comment by o-alexandrov** [comment]
@privatenumber thank you for the reply.
Let me please provide you with a [sandbox](https://stackblitz.com/edit/node-rs8fkz), so you could reproduce the issue (infinite loop).

https://user-images.githubusercontent.com/9992724/179402995-8f5ac210-6816-4a8c-b80d-ce9daf2b4c59.mov
