### ISSUE TITLE
Add ability to enable `watch` using a flag

### ISSUE THREAD

**Issue by o-alexandrov** [esbuild-kit/tsx#66]
### Feature request

Add ability to enable `watch` using a flag

### Why?

When there is already an existing npm script, ex. `package.json`:
```json
{
  "scripts": {
    "start": "tsx example.ts"
  }
}
```

There's no easy way **to start and watch**. You either need to create a bash script within an npm script or a separate npm script.

Instead, if `watch` could be enabled via a flag, then you could do:
```
$ npm run start --watch
```

or, you could make the invocation npm scripts reusable by other npm scripts.

**Comment by privatenumber** [comment]
> There's no easy way **to start and watch**. You either need to create a bash script within an npm script or a separate npm script.

Both of those solutions sound very easy to do. Personally, I create a new script for it:
```json5
{
	// ...
	"scripts": {
		// ...
		"dev": "tsx watch --conditions=development tests"
	},
	// ...
}
```

tsx needs to keep its API minimal and explicit so its clear when a flag is being passed onto tsx/Node.js vs the actual file. If we are to support watch as a flag, it would have to work similarly to Node.js, where it only gets passed into tsx if it comes _before_ the argument.

For example, in Node.js:
```
$ node --help index.js

*Shows help*

$ node index.js --help

*--help gets passed to index.js to handle*
```

Likewise, `--watch` would have to come before the arguments, so you still wouldn't be able to do `npm start -- --watch`.

Checking for the `npm_config_watch` env variable would have a similar problem too because the executed file could be using it.

**Comment by o-alexandrov** [comment]
> Both of those solutions sound very easy to do. Personally, I create a new script for it

It's an overkill and error-prone to create an additional npm script.
As well as bad for maintenance.

<details>
  <summary>Example why</summary>
  
  Imagine you have:
```json
{
  "scripts": {
    "start": "stage=production UTILS=1 NODE_ENV=production tsx example-very/very-very/long-path/env/src/helpers/cli.ts ./src/index.ts",
  }
}
```

then, based on what you described you do yourself, you'd end up with:
```json
{
  "scripts": {
    "start": "stage=production UTILS=1 NODE_ENV=production tsx example-very/very-very/long-path/env/src/helpers/cli.ts ./src/index.ts",
    "start:watch": "stage=production UTILS=1 NODE_ENV=production tsx watch example-very/very-very/long-path/env/src/helpers/cli.ts ./src/index.ts",
  }
}
```
</details>

---

> Likewise, `--watch` would have to come before the arguments, so you still wouldn't be able to do `npm start -- --watch`.

While you made a good point on using `--watch` as the postfix, we don't have to do that.
Instead, we could use a variable declared for shell only, example:

```json
{
  "scripts": {
    "start": "stage=production UTILS=1 NODE_ENV=production tsx --watch=${WATCH:=0}  example-very/very-very/long-path/env/src/helpers/cli.ts ./src/index.ts",
    "start:watch": "WATCH=1; npm run start",
  }
}
```

or you could just invoke: `WATCH=1; npm run start` w/o creating a separate script.

This is extremely important for projects with a lot of npm scripts.

**Comment by o-alexandrov** [comment]
To be precise, what is described in the previous message actually works with passing a command as well, but is kinda awkward (I'll be using it this way :D):

```json
{
  "scripts": {
    "start": "stage=production UTILS=1 NODE_ENV=production tsx $WATCH example-very/very-very/long-path/env/src/helpers/cli.ts ./src/index.ts",
    "start:watch": "WATCH=watch; npm run start",
  }
}
```
