### ISSUE TITLE
Type strictness not enforced

### ISSUE THREAD

**Issue by GeorgesOatesLarsen** [esbuild-kit/tsx#79]
### Bug description

When running typescript files with tsx, type strictness is not enforced.

This might be intentional, in which case, consider this bug report a feature request. I would like to be able to specify type strictness when compiling/using tsx.

Here is a minimal recreation of the bug/lacking feature:
https://github.com/GeorgesOatesLarsen/tsx-bug-demo

Notice the obvious type mismatch in `bug.ts`:

```ts
let x : number = "This shouldn't work...";
console.log(x);
```

It just flat out shouldn't compile by my estimate.

### Reproduction

Clone https://github.com/GeorgesOatesLarsen/tsx-bug-demo

Then run `npm install`

then run `npx tsx bug.ts`

### Environment

```shell
Running on Windows 10. No interfering global installs AFAIK.
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by rwlc** [comment]
`tsx` is powered by esbuild, which does *not* support type checking. The README itself states this:

> No, esbuild does not support type checking.

It's recommended to run TypeScript separately as a command (tsc --noEmit) or via IDE IntelliSense.

**Comment by GeorgesOatesLarsen** [comment]
I apologize that I missed that statement, sorry!
