### ISSUE TITLE
just save file and content not changed,bug can also emit watch

### ISSUE THREAD

**Issue by Valar103769** [esbuild-kit/tsx#84]
### Bug description

when i press `command + s` to save file ,the script `tsx watch ./index.ts` can restart,  the content not change, it should do nothing

.vscode/setting.json
```json
{
  "prettier.enable": false,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "npm.packageManager": "pnpm",
  "eslint.packageManager": "pnpm"
}

```

**Comment by privatenumber** [comment]
How does [nodemon](https://www.npmjs.com/package/nodemon) behave?

**Comment by privatenumber** [comment]
Closing as this behavior seems to be consistent with nodemon (what the community is used to).
