### ISSUE TITLE
How to get info about type in REPL

### ISSUE THREAD

**Issue by bondiano** [esbuild-kit/tsx#90]
### Feature request

```
> type t = string
> t
Type string
```

### Why?

It will be helpful to get typing info in REPL.

### Alternatives

Also maybe to use some specific genetic, like `Type<t>` will be nicer

**Comment by privatenumber** [comment]
tsx works by using esbuild to strip out types so Node.js can run it.

I recommend using [`ts-node`](https://github.com/TypeStrong/ts-node) for that.
