### ISSUE TITLE
Missing --keep-names flag results in useless sourcemaps

### ISSUE THREAD

**Issue by npearson72** [esbuild-kit/tsx#98]
### Bug description

Sourcemaps that are generated refer to esbuild minified files that have renamed variables, which means that DevTools for Node.js can't access the sourcemap variables while debugging.

### Reproduction

Simply start any Express server with Typescript using:

`tsx watch --inspect --clear-screen=false src/index.ts`

Throw in a `debugger` in any endpoint and launch your DevTools for Node.js.

You'll see that the `req` variable (for example) is unavailable because the minified file that the sourcemap points to doesn't have this variable.

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 295.01 MB / 16.00 GB
    Shell: 5.9 - /usr/local/bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.asdf/installs/nodejs/16.15.1/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 8.11.0 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.05.30.00 - /usr/local/bin/watchman
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by npearson72** [comment]
@privatenumber I just tested. It seems to partially work. But for some reason I'm losing variables.

Here's an example... my code:

```
...
const create = async (req: Request, res: Response) => {
  try {
    const user = await validateNewUserSchema(req.body);
  } catch (e) {
    debugger;
  }
...
```

Looking at the source code from the map, I'm missing the `e`:

```
const create = __name(async(req,res)=>{
    try {
        const user2 = await (0,
        import_schemas.validateNewUserSchema)(req.body)
    } catch {
        debugger
    }
```

**Comment by privatenumber** [comment]
Will reopen to disable minifySyntax to prevent [unused variables from being removed](https://hyrious.me/esbuild-repl/?version=0.15.7&mode=transform&input=try+%7B%0A%7D+catch+%28e%29+%7B%0A++const+a+%3D+1%3B%0A++debugger%3B%0A%7D&options=--loader%3Dts+--minify-syntax).

**Comment by privatenumber** [comment]
@npearson72 

Fixed in https://github.com/esbuild-kit/core-utils/pull/29, but as the PR says, note:
> Unused variables are no longer deleted, but variable names may not be preserved since esbuild could rename them: https://github.com/esbuild-kit/tsx/issues/98

This is not really an esbuild issue but a limitation in the debugger you're using. Please make a feature request to the debugger you're using to support the `names` property in source maps.

**Comment by npearson72** [comment]
Thank you! I'll look into submitting a ticket with Chromium.

**Comment by privatenumber** [comment]
If it's Chromium, it's likely they already support `names`, and this was an issue with the unused variable getting removed by esbuild.

Please double check to see if something like this works:

```js
const error = 'should not be evaluated';
try {
	throw 'should be evaluated';
} catch (error) {
	debugger;
	// evaluate `error` to see 'should be evaluated'
}
```

**Comment by npearson72** [comment]
Sad to say that it doesn't work:

<img width="887" alt="Screen Shot 2022-09-21 at 10 11 42 AM" src="https://user-images.githubusercontent.com/1323414/191568722-a04884f6-6b8a-4fb8-96c8-3f2639d0460f.png">

I'm using Chrome `Version 105.0.5195.125 (Official Build) (x86_64)`

**Comment by privatenumber** [comment]
Just to be sure, you're using https://github.com/esbuild-kit/core-utils/releases/tag/v2.3.2 right? And does `error2` log fine?

**Comment by npearson72** [comment]
I believe so:

```
➜ yarn why @esbuild-kit/core-utils
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "@esbuild-kit/core-utils"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@esbuild-kit/core-utils@2.3.2"
info Has been hoisted to "@esbuild-kit/core-utils"
info Reasons this module exists
   - Specified in "devDependencies"
   - Hoisted from "tsx#@esbuild-kit#core-utils"
   - Hoisted from "tsx#@esbuild-kit#cjs-loader#@esbuild-kit#core-utils"
   - Hoisted from "tsx#@esbuild-kit#esm-loader#@esbuild-kit#core-utils"
info Disk size without dependencies: "88KB"
info Disk size with unique dependencies: "332KB"
info Disk size with transitive dependencies: "1.15MB"
info Number of shared dependencies: 2
✨  Done in 0.11s.
```

`yarn.lock`:

```
"@esbuild-kit/core-utils@2.3.2", "@esbuild-kit/core-utils@^2.1.0":
  version "2.3.2"
  resolved "https://registry.yarnpkg.com/@esbuild-kit/core-utils/-/core-utils-2.3.2.tgz#c2adcc8e84bb05fab242386fd3d226eb5711468f"
  integrity sha512-aQwy1Hdd02ymjyMyyrhtyuZGv5W+mVZmj3DTKFV0TnB1AUgMBV40tXySpsGySe8vLvSe0c0TaqTc2FUo8/YlNQ==
  dependencies:
    esbuild "~0.15.7"
    source-map-support "^0.5.21"
```

Still getting the same as before:

<img width="720" alt="Screen Shot 2022-09-21 at 10 52 04 AM" src="https://user-images.githubusercontent.com/1323414/191576562-59db414b-7511-45fb-9299-b33c8348dc7d.png">

And yes, `error2` resolves.

**Comment by npearson72** [comment]
I've created a repo in case you're interested:

https://github.com/npearson72/tsx-debug

Just use postman or whatever and send a `POST` to: `http://localhost:4000/api/v1/users`

**Comment by privatenumber** [comment]
I'm able to reproduce not being able to accurately evaluate the variable names from the sourcemap.

However, we can see that Chrome is reading the sourcemap's `names` property because it shows up correctly in the side-bar under "Scope".

<img width="629" alt="Screen Shot 2022-09-22 at 4 06 57 PM" src="https://user-images.githubusercontent.com/1075694/191680877-63ddc0a9-5711-41e4-8748-88eea46de24a.png">

I think this is a limitation with Chrome's console not mapping the inputted variables to the sourcemap's variables. It might not always be possible (eg. when the variable is deleted by a minifier because it's unused) but feel free to file a feature request with Chrome.

At the least, maybe there could be a way to see the variable name it transformed to so you can type it into the console.

----

FYI you can reproduce with a file just with the try-catch without a server:
```js
const error = 'no show';
try {
	throw 'show';
} catch (error) {
	console.log(error);
	debugger;
}
```

**Comment by npearson72** [comment]
Thanks for looking into this. I think I can work with this as it stands. It's much better than before we first started discussing this issue. I appreciate your help..

**Comment by privatenumber** [comment]
Unfortunately, it might have to be reverted as a result of this regression:
https://github.com/evanw/esbuild/issues/2573

**Comment by npearson72** [comment]
That is a pity
